### ISSUE TITLE
Invalid session

### ISSUE THREAD

**Issue by uberdeveloper** [5paisa/py5paisa#10]
Hi
@invinciblycool 

* 5paisa Python SDK version: 0.1.5
* Python version: 3.6.10

### Description

Keep getting `invalid session` message

### What I Did

* I tried the python API but could not log in
* I tried with a fresh requests object and could log in but I cannot get any other method working either in Python or Javascript
* A plain POST request over [reqbin](https://reqbin.com/) also fails. 

I get the following errors when running calling the positions URL
```
{
    "body": {
        "Message": "Invalid Session",
        "NetPositionDetail": [],
        "Status": 9
    },
    "head": {
        "responseCode": "5PNPNWV1",
        "status": "0",
        "statusDescription": "Invalid Session"
    }
}
```

and the following error when requesting the margins URL
```
{
    "body": {
        "ClientCode": "59808196",
        "EquityMargin": [],
        "Message": "Invalid Session",
        "Status": 9,
        "TimeStamp": "\/Date(1598626953085+0530)\/"
    },
    "head": {
        "responseCode": "5PMarginV3",
        "status": "0",
        "statusDescription": "Success"
    }
}
```

**Comment by invinciblycool** [comment]
Hello @uberdeveloper 
Please make sure you have a `keys.conf` file in the same directory as your main python file.
The conf file should contain all the keys required for authentication.
Please refer to the docs [here](https://5paisa.github.io/usage/auth/)

**Comment by invinciblycool** [comment]
Once you get your authentication right, all errors will be resolved.
Let me know if you face any further problems.

**Comment by uberdeveloper** [comment]
Hi @invinciblycool 
Tried a python 3.7 virtual environment and logged in but cannot get any other method working.
`client.order_book()` only displays time
`client.margin()` shows the following error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-1b3f47e43290> in <module>
----> 1 client.margin()

~/anaconda3/lib/python3.6/site-packages/py5paisa/py5paisa.py in margin(self)
     60 
     61     def margin(self):
---> 62         return self._user_info_request("MARGIN")
     63 
     64     def order_book(self):

~/anaconda3/lib/python3.6/site-packages/py5paisa/py5paisa.py in _user_info_request(self, data_type)
     95         payload["head"]["requestCode"] = request_code
     96         response = self.session.post(url, json=payload, headers=HEADERS).json()
---> 97         message = response["body"]["Message"]
     98         if message != "Success":
     99             log_response(message)

TypeError: 'NoneType' object is not subscriptable
```

**Comment by invinciblycool** [comment]
Can you update the SDK to the latest release `pip install py5paisa==0.1.5`

Also, it just shows you the log time because your order book is empty.

**Comment by uberdeveloper** [comment]
It is already at  py5paisa==0.1.5
```
certifi==2020.6.20
chardet==3.0.4
idna==2.10
loguru==0.5.1
pbkdf2==1.3
py5paisa==0.1.5
pycryptodome==3.9.8
requests==2.24.0
urllib3==1.25.10
```

I placed an amo via web version and also placed a canceled order but they do not show up

**Comment by invinciblycool** [comment]
I hope you're not getting any errors?
Also, not sure if rejected orders show up.

**Comment by uberdeveloper** [comment]
Sure, I am not getting any errors since time gets printed.
But my expectation is all orders should show up irrespective of AMO or canceled or rejected.
Maybe, I would try this in market hours and see how this works and report back.

Are you from 5paisa?
Thanks for the response

**Comment by uberdeveloper** [comment]
Also, could you change the return values to a list instead of None for the methods so that we could have a reasonable return value based on the type of output?
Should I raise a separate issue for this?

**Comment by invinciblycool** [comment]
> Also, could you change the return values to a list instead of None for the methods so that we could have a reasonable return value based on the type of output?
> Should I raise a separate issue for this?

Yes, please. Raising a separate issue with more details will be better.
Also, let me know the status of this issue.

**Comment by uberdeveloper** [comment]
You could close this thread since the original invalid session error do not arise with Python 3.7

**Comment by invinciblycool** [comment]
Thanks!
Feel free to open issues if any!

**Comment by abhay4951** [comment]
whenever i am hitting https://Openapi.5paisa.com/VendorsAPI/Service1.svc/V2/OrderBook API from postman i am getting a response but when i try same request through java sdk getting below response -
{"body":{"Message":"Invalid Session","OrderBookDetail":[],"Status":9},"head":{"responseCode":"5POrdBkV2","status":"0","statusDescription":"Success"}}

this is strange, have executed login API call before calling orderBook API through java sdk.

**Comment by abhay4951** [comment]
is it because of caching mechanism?
