### ISSUE TITLE
Ironfly strategy issues

### ISSUE THREAD

**Issue by ThetaGainer** [5paisa/py5paisa#105]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

I was trying to deploy Ironfly on banknifty

### What I Did

```
strategy.iron_fly("banknifty",["37900","38900"],"38400","25","20211014","D")

```
3 leg executed and 1 leg rejected due to margin requirement.
the 3 leg remain active and open and did not get cancelled.

**Comment by 5paisa** [comment]
Hi @ThetaGainer ,

This has to be checked by the user of this strategy module if some leg does not go through.
As this does not guarantee execution!
