### ISSUE TITLE
Missing Print In Documentation

### ISSUE THREAD

**Issue by kalilinux-png** [5paisa/py5paisa#106]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description
missed just a little print 

Describe what you were trying to get done.
#NOTE : Symbol has to be in the same format as specified in the example below.

    req_list_=[{"Exch":"N","ExchType":"D","Symbol":"NIFTY 22 APR 2021 CE 15200.00","Expiry":"20210422","StrikePrice":"15200","OptionType":"CE"},
                {"Exch":"N","ExchType":"D","Symbol":"NIFTY 22 APR 2021 PE 15200.00","Expiry":"20210422","StrikePrice":"15200","OptionType":"PE"}]
                
    print(client.fetch_market_feed(req_list_))

Tell us what happened, what went wrong, and what you expected to happen.

 print(client.fetch_market_feed(req_list_))

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by 5paisa** [comment]
Seems to be fine!
