### ISSUE TITLE
Streming_data function issue

### ISSUE THREAD

**Issue by salilshukla9** [5paisa/py5paisa#108]
Streming_data function can not be used in our code, as when we run it it continuously runs up and we can capture any values like 5 level market depth through it, we only can see it s output continuously printing again and again, my suggestion is that it should stop after one time execution then anyone can use it in their codes.

![image](https://user-images.githubusercontent.com/44822052/141060644-f599c205-3227-4fe4-a31f-64953fb07894.png)

**Comment by salilshukla9** [comment]
Actually i want to sum up the active buyers or active sellers quantity i.e up to 5 bids only..Totalbuyquantity dont fulfill requirement as it has a lot manupulated orders only

**Comment by gvijaygvk** [comment]
I am also facing the same issue, unable to capture the streaming data... and use it in algo

**Comment by saikrisshnaa** [comment]
@salilshukla9  @gvijaygvk  As I can understand from your comments, the requirement is to use the live market feed in your code. As the api method provided by 5paisa is an blocking method, one needs to create a new thread and use that thread for creating socket connection and listening to live market feed stream.  The main thread then can be used to consume the live market data.

**Comment by Parthiban-Sampath** [comment]
Streming_data in py5paisa can be modified using json.loads() to store it in any of the file. 
And access from respective files. 

def Streming_data(self,wsPayload : dict):
self.web_url=f'wss://openfeed.5paisa.com/Feeds/api/chat?Value1={self.Jwt_token}|{self.client_code}'
        auth=self.Login_check()
        import csv
        fieldnames = ['price']
        def on_message(ws, message):
            for msg in json.loads(message):
            	required = {'price':msg['LastRate']}
            	with open('scrips/' + str(msg['Token']) + '.csv','a') as csvfile:
            		csv_writer = csv.DictWriter(csvfile,fieldnames = fieldnames)
            		csv_writer.writerow(required)

Here, everytime when it calls on_message(), it returns a string. I have passed the string to json.loads(). From json data, I have taken the price info and storing it in a csv file. And you can access externally for your analysis or any purpose.

**Comment by salilshukla9** [comment]
> Streming_data in py5paisa can be modified using json.loads() to store it in any of the file. And access from respective files.
> 
> def Streming_data(self,wsPayload : dict): self.web_url=f'wss://openfeed.5paisa.com/Feeds/api/chat?Value1={self.Jwt_token}|{self.client_code}' auth=self.Login_check() import csv fieldnames = ['price'] def on_message(ws, message): for msg in json.loads(message): required = {'price':msg['LastRate']} with open('scrips/' + str(msg['Token']) + '.csv','a') as csvfile: csv_writer = csv.DictWriter(csvfile,fieldnames = fieldnames) csv_writer.writerow(required)
> 
> Here, everytime when it calls on_message(), it returns a string. I have passed the string to json.loads(). From json data, I have taken the price info and storing it in a csv file. And you can access externally for your analysis or any purpose.

Thanks Parth,

It works for 'mf' but not for 'md' request feed, in case of 'md' it does not return data as prints on my very first screenshot. just return as "Time" in my csv file. you may also try for the case of 'md' and save 'NumberOfOrders' in csv file, it will not work. even I try to print 'msg' in csv file but only  text 'Time' was saved in csv file.
