### ISSUE TITLE
cannot import exchange type from order.py

### ISSUE THREAD

**Issue by jugs695369** [5paisa/py5paisa#11]
Traceback (most recent call last):
  File "E:\jugs\n\test_h.py", line 2, in <module>
    from py5paisa.order import Order, OrderType, Exchange,OrderForStatus, ExchangeType, RequestList
ImportError: cannot import name 'ExchangeType' from 'py5paisa.order' (C:\Users\satish\AppData\Local\Programs\Python\Python37\lib\site-packages\py5paisa\order.py)

**Comment by invinciblycool** [comment]
Change `ExchangeType` to `ExchangeSegment`

**Comment by invinciblycool** [comment]
Also make sure you're using the latest version of py5paisa.

`pip install py5paisa==0.1.5`

**Comment by invinciblycool** [comment]
Please close this issue if it worked @jugs695369

**Comment by uberdeveloper** [comment]
> Change `ExchangeType` to `ExchangeSegment`

This solves the import error
