### ISSUE TITLE
Unable to place normal order 

### ISSUE THREAD

**Issue by kasrthiksacoe** [5paisa/py5paisa#111]
* 5paisa Python SDK version:latest
* Python version:3.10.0
* Operating System:windows

### Description

placing normal order :

### What I Did

test_order = Order(order_type='B',exchange='N',exchange_segment='C', scrip_code = 1660, quantity=1, price=236.5,is_intraday=True)
client.place_order(test_order)

Error message 
'BrokerOrderID': 0,
 'ClientCode': '53621786',
 'Exch': 'N',
 'ExchOrderID': '',
 'ExchType': 'C',
 'LocalOrderID': 0,
 'Message': 'Error while processing your request.',
 'RMSResponseCode': -1,
 'ScripInfo': '1660',
 'Status': -1,
 'Time': '/Date(1638507394170+0530)/'}

```

**Comment by kasrthiksacoe** [comment]
Can anyone help me in this ?

**Comment by 5paisa** [comment]
Hi @kasrthiksacoe ,

Can you retry now with updated code?
