### ISSUE TITLE
Error while getting the data on socket

### ISSUE THREAD

**Issue by rajasekharnerella** [5paisa/py5paisa#114]
* 5paisa Python SDK version: Latest
* Python version: 3.8
* Operating System: MAC Catalina

### Description

Trying to get the streaing of the data for intraday on scoket. Am getting the error as below:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)
on_close() takes 1 positional argument but 3 were given

### What I Did

```
req_list=[{ "Exch":"N","ExchType":"C","ScripCode":1660}, ]
dict1=client.Request_Feed('mf','s',req_list)
client.Streming_data(dict1)
```

**Comment by rishabhmaniyar** [comment]
Code is updated in new release

**Comment by 5paisa** [comment]
Hi @rajasekharnerella ,

Websocket code has been updated in new release of 0.4.1

**Comment by 5paisa** [comment]
Yes this has been fixed now in documentation as well!
