### ISSUE TITLE
Unable to place order in bank nifty weekly expiry option 

### ISSUE THREAD

**Issue by kumarchinmaya116** [5paisa/py5paisa#115]
I had a doubt regarding the order placement. How can I place orders on bank nifty weekly expiry options, as the scrip codes available in the scrip master as for monthly expiry options only, and the other method in which I can place orders by scrip data gives error as "invalid Scripdata" when I place an order. I have tried with the exact format as given in the scripmaster, still it would not place order.
Here is what I did:
```
test_order = Order(order_type='B',exchange='N',exchange_segment='D', scripdata = 'BANKNIFTY 09 Dec 2021 CE 37300.00', quantity=25, price=0,is_intraday=False)
client.place_order(test_order)
print("long position created")
```

**Comment by kasrthiksacoe** [comment]
try this format 
Options scrip : "NIFTY 30 Sep 2021 CE 11000.00_20210930_CE_1100 0" (symbol,expiry, call/put, strikerate)
