### ISSUE TITLE
Second Factor Authentication Failed

### ISSUE THREAD

**Issue by 12345k** [5paisa/py5paisa#117]
* 5paisa Python SDK version:  0.3.6
* Python version: 3.8.0
* Operating System: Linux

### Description

I am trying to login with API credential and I am getting this error.I put my code below. kindly check out and let me know your feedback

### What I Did

```import os
from dotenv import load_dotenv
from py5paisa import FivePaisaClient
from py5paisa.order import Order, OrderType, Exchange
env_path = os.path.join(os.getcwd(), 'user_1.env')
load_dotenv(dotenv_path=env_path)

cred ={
            "APP_NAME":os.getenv("APP_NAME"),
            "APP_SOURCE":os.getenv("APP_SOURCE"),
            "USER_ID":os.getenv("USER_ID"),
            "PASSWORD":os.getenv("PASSWORD"),
            "USER_KEY":os.getenv("USER_KEY"),
            "ENCRYPTION_KEY":os.getenv("ENCRYPTION_KEY"),
            "user":os.getenv("user"),
            "pass":os.getenv("pass"),
            "dob":os.getenv("dob"),
        }

client = FivePaisaClient(email=cred["user"], passwd=cred["pass"], dob=cred["dob"],cred=cred)
client.login()


Output:
15:28:30 | Second Factor Authentication Failed"
```

**Comment by pranav118899** [comment]
it's a shitty APIs with no documentation. they won't reply to anything.

**Comment by Parthiban-Sampath** [comment]
cred dict should have only the following keys:

cred={
    "APP_NAME":"YOUR APP_NAME",
    "APP_SOURCE":"YOUR APP_SOURCE",
    "USER_ID":"YOUR USER_ID",
    "PASSWORD":"YOUR PASSWORD",
    "USER_KEY":"YOUR USERKEY",
    "ENCRYPTION_KEY":"YOUR ENCRYPTION_KEY"
    }

In your code, you have defined extra keys. Remove those and try it.

**Comment by Parthiban-Sampath** [comment]
> * 5paisa Python SDK version:  0.3.6
> * Python version: 3.8.0
> * Operating System: Linux
> 
> ### Description
> I am trying to login with API credential and I am getting this error.I put my code below. kindly check out and let me know your feedback
> 
> ### What I Did
> ```
> from dotenv import load_dotenv
> from py5paisa import FivePaisaClient
> from py5paisa.order import Order, OrderType, Exchange
> env_path = os.path.join(os.getcwd(), 'user_1.env')
> load_dotenv(dotenv_path=env_path)
> 
> cred ={
>             "APP_NAME":os.getenv("APP_NAME"),
>             "APP_SOURCE":os.getenv("APP_SOURCE"),
>             "USER_ID":os.getenv("USER_ID"),
>             "PASSWORD":os.getenv("PASSWORD"),
>             "USER_KEY":os.getenv("USER_KEY"),
>             "ENCRYPTION_KEY":os.getenv("ENCRYPTION_KEY"),
>             "user":os.getenv("user"),
>             "pass":os.getenv("pass"),
>             "dob":os.getenv("dob"),
>         }
> 
> client = FivePaisaClient(email=cred["user"], passwd=cred["pass"], dob=cred["dob"],cred=cred)
> client.login()
> 
> 
> Output:
> 15:28:30 | Second Factor Authentication Failed"
> ```

cred dict should have only the following keys:

cred={
"APP_NAME":"YOUR APP_NAME",
"APP_SOURCE":"YOUR APP_SOURCE",
"USER_ID":"YOUR USER_ID",
"PASSWORD":"YOUR PASSWORD",
"USER_KEY":"YOUR USERKEY",
"ENCRYPTION_KEY":"YOUR ENCRYPTION_KEY"
}

In your code, you have defined extra keys. Remove those and try it.

**Comment by 5paisa** [comment]
Hi ,

DOB is 2FA.
It should be in "yyyymmdd" format

**Comment by shotu** [comment]
Doesn't matter it keeps failing with the same error. I tried both the formats "yyyymmdd" and  "ddmmyyyy"
