### ISSUE TITLE
Placeorder and modify order functions not working

### ISSUE THREAD

**Issue by DONGHOSH** [5paisa/py5paisa#119]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

I am trying to place order using the SDK functions but the orders are not going through. All other API functions are working other than placeorder and modifyorder.
I get the following error 

'BrokerOrderID': 0,
 'ClientCode': 'xxxxxxxxx',
 'Exch': 'N',
 'ExchOrderID': '0',
 'ExchType': 'C',
 'LocalOrderID': 0,
 'Message': 'Error while processing your request.',
 'RMSResponseCode': -1,
 'ScripInfo': '1660',
 'Status': -1,
 'Time': '/Date(1641361765137+0530)/'}

### What I Did

```
test_order = Order(order_type='B',exchange='N',exchange_segment='C', scrip_code = 1660, quantity=1, price=210.5,is_intraday=False)

client.place_order(test_order)
```

**Comment by 5paisa** [comment]
This has been fixed in update.
Please update to 0.3.7 package!
