### ISSUE TITLE
API Limit exceeded Exception

### ISSUE THREAD

**Issue by uberdeveloper** [5paisa/py5paisa#12]
There is an API Limit of 10 requests per minute.

1.  Is this for the entire API or only placing orders?
2.  How to know that the API Limit is exceeded? Is there a built-in exception or a header response or a json response to identify this
3. Can the API Limit be increased?

**Comment by invinciblycool** [comment]
Answeing points 2 and 3.

Currently there is no way to know if you have exceeded the API limit.
Yes, you can write to support@5paisa.com to increase your API limits.
Let me get back to you on point 1.

**Comment by invinciblycool** [comment]
The API limit has been extended to 50 requests per minute.
And this limit applies only to order placement.

**Comment by invinciblycool** [comment]
Please close this is all your questions were answered.

**Comment by invinciblycool** [comment]
Please close this is all your questions were answered.

**Comment by uberdeveloper** [comment]
Thanks for the clarification.
This issue could be closed
