### ISSUE TITLE
place_order throws "Error while processing your request." while placing an order request

### ISSUE THREAD

**Issue by mithunpradeep** [5paisa/py5paisa#121]
* 5paisa Python SDK version: 0.3.6
* Python version: 3.9
* Operating System: MacOS

### Description

place_order API throws "Error while processing your request.", while placing an order request.

API was working as expected till yesterday.

### What I Did

```
client.login()
order = Order(order_type='B', exchange='N', exchange_segment='D', is_intraday=False, quantity=1000,
                  scrip_code=39588, price=0)
client.place_order(order)

 12:14:31 | Logged in!!
 12:14:31 | Error while processing your request.

```

**Comment by 5paisa** [comment]
Hi @mithunpradeep ,

This has been fixed in update.
Please update to 0.3.7 package!
