### ISSUE TITLE
Not able to login- no LOGIN_ROUTE py5paisa version 0.4.1

### ISSUE THREAD

**Issue by DONGHOSH** [5paisa/py5paisa#123]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

client.login()
client.orderbook()

Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```

If there was a crash, please include the traceback here.
```
![no_login](https://user-images.githubusercontent.com/97148400/148627787-cccaf1a9-73e1-45ef-8d6f-1a2185b7696b.jpg)

**Comment by 5paisa** [comment]
Hi,

Can you please update to the latest package and try again.

**Comment by qalpesh** [comment]
> Hi,
> 
> Can you please update to the latest package and try again.

I request you, in future, to update the 5paisa package on weekends or atleast after market hours, yesterday the code was changed during the market hours and my Algo strategy went for a toss. Thank you

**Comment by 5paisa** [comment]
Hey @qalpesh ,

We don't put updates during market hours until it is very important.
Still thanks for your feedback!

**Comment by DONGHOSH** [comment]
> Hi,
> 
> Can you please update to the latest package and try again.

Hi, I have updated to the latest version, after uninstalling the previous version. Current **version is 0.4.1**

I am still not able to login
Getting the following error

client.login()
 12:15:38 | 'FivePaisaClient' object has no attribute 'LOGIN_ROUTE'

client.margin()
 12:17:04 | 'FivePaisaClient' object has no attribute 'MARGIN_ROUTE'

client.order_book()
 12:17:23 | 'FivePaisaClient' object has no attribute 'ORDER_BOOK_ROUTE'

client.get_tradebook()
 12:17:46 | 'FivePaisaClient' object has no attribute 'TRADEBOOK_ROUTE'

client.positions()
 12:18:11 | 'FivePaisaClient' object has no attribute 'POSITIONS_ROUTE'

client.holdings()
 12:18:33 | 'FivePaisaClient' object has no attribute 'HOLDINGS_ROUTE'

**Comment by 5paisa** [comment]
Hi,

Please share your code (hide you account login information)
Will check and get back with solution

**Comment by DONGHOSH** [comment]
Issue has been resolved 

Best,
Don
