### ISSUE TITLE
Cannot get any method other than login

### ISSUE THREAD

**Issue by uberdeveloper** [5paisa/py5paisa#13]
Only the `client.login` method works.
Other methods either raise an error or prints only the timestamp
When I run, `client.order_book()`, I get this output

`13:24:25 | `
I have both live pending orders and positions
When I checked at the start of the day, it displayed `No orders`

I tried a plain python request using the session object like this
```python
import json
payload = {
    "head": client.payload['head'],
    "body": {
        "clientCode": client.client_code
    }
}
payload['head']['requestCode'] = client.ORDER_BOOK_REQUEST_CODE
req = client.session.post(url=client.ORDER_BOOK_ROUTE, data=json.dumps(payload),
                    headers={'Content-Type': 'application/json'})
```

I get the following output
```
{'body': {'Message': 'Error while processing your request.',
  'OrderBookDetail': [],
  'Status': -1},
 'head': {'responseCode': '5POrdBkV2',
  'status': '0',
  'statusDescription': 'Success'}}
```

**Comment by uberdeveloper** [comment]
Tried the provided POSTMAN api methods and still get the same error

**Comment by uberdeveloper** [comment]
@invinciblycool @5paisa 
Any update on this.
Since this is required to check my live orders and positions

**Comment by invinciblycool** [comment]
Noted. I'm working on this.
Will push a fix today

**Comment by invinciblycool** [comment]
The latest commit fixes the issue.
Please update to the latest version by running `pip install py5paisa==0.1.6`
Let me know if it worked for you.
Also, thanks a ton for reporting the issue.

**Comment by uberdeveloper** [comment]
@invinciblycool 
Works perfectly :+1: 

`client.margin()` still throws an error

**Comment by invinciblycool** [comment]
`client.margin()` works fine for me with the latest fix.
Please double check or share your snippet here.

**Comment by invinciblycool** [comment]
Closing this until then, feel free to open a new issue!
