### ISSUE TITLE
client.fetch_market_depth(a)  function not working

### ISSUE THREAD

**Issue by vinayakbhovi** [5paisa/py5paisa#130]
code:

a=[{"Exchange":"N","ExchangeType":"C","ScripCode": "843567"}]
client.fetch_market_depth(a)

output
[/usr/local/lib/python3.7/dist-packages/py5paisa/py5paisa.py](https://localhost:8080/#) in order_request(self, req_type)
    216                                 headers=HEADERS).json()
    217 
--> 218         log_response(res["body"]["Message"])
    219         return res["body"]
    220 

KeyError: 'body'

**Comment by 5paisa** [comment]
This issue is now resolved!
