### ISSUE TITLE
Invalid time frame for 30min historic data 

### ISSUE THREAD

**Issue by kasrthiksacoe** [5paisa/py5paisa#133]
* 5paisa Python SDK version: latest
* Python version:
* Operating System: windows

### Description
30 min historic api returns wrong time frames instead of  9:45 for the first 30 min candle it displays 09-15, 9:30,10:00 time frame 

### What I Did

```
client.historical_data('N','D',51868,'30m','2022-02-14','2022-02-14')

```

**Comment by 5paisa** [comment]
@kasrthiksacoe ,

This has been fixed now!

Thank you
