### ISSUE TITLE
Not able to fetch the Order status to get remote ID

### ISSUE THREAD

**Issue by intronix** [5paisa/py5paisa#136]
5paisa Python SDK version: v0.4.1-pre-alpha
    Python version: 3.8
    Operating System: Windows 11/10/Raspberry Pi

Description

On Successful placing of the order, i tried to get the status of the order based on RemoteId , but fetch order order status has returned empty

req_list_= [

    {
        "Exch": "N",
        "RemoteOrderID": "ST_11444"
    }]

Fetches the order status

client.fetch_order_status(req_list_)

Error message

 10:47:52 | Logged in!!
 10:47:53 | Invalid input parameters.
{'Message': 'Invalid input parameters.', 'OrdStatusResLst': [], 'Status': 3}

**Comment by Ganesh-ops** [comment]
Even I have same issues

**Comment by 5paisa** [comment]
Hi @intronix ,

This issue has been fixed in the last release 0.4.3
