### ISSUE TITLE
Live Market Feed Streaming (error solved)

### ISSUE THREAD

**Issue by viveknariya** [5paisa/py5paisa#138]
#Syntex error in Live Market Feed Streaming

### What I Did
req_list=[
            { "Exch":"N","ExchType":"C","ScripCode":1660},
            ]

req_data=client.Request_Feed('mf','s',req_list)
def on_message(ws, message):
    print(message)

client.connect(**dict1**)

#use **req_data** instead **dict1**

client.receive_data(on_message)

**Comment by 5paisa** [comment]
Thanks you corrected it!
