### ISSUE TITLE
Can I get live price ticks of any script

### ISSUE THREAD

**Issue by rakesh146** [5paisa/py5paisa#14]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by invinciblycool** [comment]
Please check https://www.5paisa.com/developerapi/websocketformarketfeeds

**Comment by srikanthbojja** [comment]
@rakesh146 did you get this working in your python script?

**Comment by shalabhgoel13** [comment]
does someone know what values should come here??

"body": {
    "userId" : "<<Vendor Encrypted UserID>>",
    "password": "<<Vendor Encrypted Password>>"
    }

**Comment by shalabhgoel13** [comment]
Can someone please look at the code and tell me what is wrong in the input paramaters??

**Comment by coder-amogh** [comment]
> Please check https://www.5paisa.com/developerapi/websocketformarketfeeds

Is there any Pythonic way of doing it? Some function or class?

**Comment by coder-amogh** [comment]
I tried this: but I get status code as `400` and 

### Response as:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Request Error</title>
    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>
  </head>
  <body>
    <div id="content">
      <p class="heading1">Request Error</p>
      <p>The server encountered an error processing the request. See server logs for more details.</p>
    </div>
  </body>
</html>
```

### Code I used:

```
import requests

url = "https://Openapi.5paisa.com/VendorsAPI/Service1.svc/MarketFeed"

data = {
	"head": {
		"appName": "5P523xxxxx",
		"appVer": "1.0",
		"key": "xxxxxxx",
		"osName": "WEB",
		"requestCode": "5PMF",
		"userId": "xxxxxx",
		"password": "xxxxxx"
	},
	"body": {
		"Count": 1,
		"MarketFeedData": [
			{
				"Exch": "N",
				"ExchType": "C",
				"Symbol": "BHEL",
				"Expiry": "",
				"StrikePrice": "0",
				"OptionType": ""
			},
		],
		"ClientLoginType": 0,
		"LastRequestTime": "/Date(0)/",
		"RefreshRate": "H"
	}
}

headers = {
	"Content-Type": 'application/json'
}

r = requests.post(url, data = data, headers = headers)

print(r.status_code)

try:
	print(r.text)
except Exception as e:
	print(f'ERROR: {e}')
```

**Comment by shalabhgoel13** [comment]
url = "https://openapi.5paisa.com/VendorsAPI/Service1.svc/MarketFeed"
response = requests.post(url,json=data)
print(response.json())

use this code. No need to set headers to json.

**Comment by shalabhgoel13** [comment]
Also there will not be a comma in between } and ] for marketfeed. I am not using any and able to fetch data

**Comment by coder-amogh** [comment]
> try this, please do tell me if this worked for you or not?

Yay! It finally worked, thanks a ton man!

> BTW by looking at your code, I got the mistake I was doing and finally am able to fetch data .. Thanks a lot. This is the output

Cool! :+1:

**Comment by shalabhgoel13** [comment]
happy to help :+1:

**Comment by coder-amogh** [comment]
@shalabhgoel13 Can you please help me with this issue: #33?
The team is not even getting in touch... So we'll all have to figure out ourselves somehow :disappointed:

**Comment by salilshukla9** [comment]
while using "client.Streaming_data(dict1)" I get repetitive live data, but when I want to access the data in any way it always start streaming and no able to access the data of that list coming from server. see the screenshot of code attached
<img width="531" alt="Streaming_data" src="https://user-images.githubusercontent.com/44822052/118034023-22c19180-b387-11eb-9d4e-0009ebe5c7cc.png">
:-
