### ISSUE TITLE
cannot make head and tail out of this 

### ISSUE THREAD

**Issue by srinidhihebbar260297** [5paisa/py5paisa#143]
20:40:38 | Logged in!!
 20:40:39 | 'head'
 20:40:39 | 'NoneType' object is not subscriptable
None
 20:40:39 | 'body'
 20:40:39 | 'body'
 20:40:39 | 'body'
 20:40:39 | 'body'
 20:40:39 | 'body'

**Comment by srinidhihebbar260297** [comment]
reverted back to version 4.1 from 4.3 it is working fine as of now

**Comment by 5paisa** [comment]
Please share the request that gave this response!

**Comment by srinidhihebbar260297** [comment]
# Fetches holdings
client.holdings()

# Fetches margin
client.margin()

# Fetches positions
client.positions()

# Fetches the order book of the client
client.order_book()

# Fetches Trade book
client.get_tradebook()



This is not working in version 0.4.3 but working fine with 0.4.1
