### ISSUE TITLE
How to stop streaming

### ISSUE THREAD

**Issue by mpunekar** [5paisa/py5paisa#150]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

I'm using jupyter notebook to test streaming functionality of your APIs and able to stream live data using the code given on your github page. However, I'm unable to understand how to stop the streaming? Can you please suggest how to stop streaming once its started?

I defined a following dummy function 

def on_exit_message(ws, message):
    print("Streaming Stopped")

and then wrote following code within the "on_message" function
    req_data_1=client.Request_Feed('mf','u',req_list)
    client.connect(req_data_1)
    client.receive_data(on_exit_message)

This did stop the streaming after first instance of function "on_message(ws, message)" was called however, the statements written after 
client.receive_data(on_message)
weren't executed until I clicked "interrupt the kernel" tab in my jupyter notebook. 

Can you please suggest what can I do to stop the streaming?

Mayur

**Comment by mpunekar** [comment]
@5paisa please answer my above question regarding streaming.

**Comment by apurva2307** [comment]
You can use client.close_data() to stop the streaming.
