### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by vinayakbhovi** [5paisa/py5paisa#158]
SSLError                                  Traceback (most recent call last)
~/.conda/envs/default/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702             # Make the request on the httplib connection object.
--> 703             httplib_response = self._make_request(
    704                 conn,

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385         try:
--> 386             self._validate_conn(conn)
    387         except (SocketTimeout, BaseSSLError) as e:

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1039         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1040             conn.connect()
   1041 

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/connection.py in connect(self)
    413 
--> 414         self.sock = ssl_wrap_socket(
    415             sock=conn,

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    448     if send_sni:
--> 449         ssl_sock = _ssl_wrap_socket_impl(
    450             sock, context, tls_in_tls, server_hostname=server_hostname

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/util/ssl_.py in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    492     if server_hostname:
--> 493         return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    494     else:

~/.conda/envs/default/lib/python3.9/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    499         # ctx._wrap_socket()
--> 500         return self.sslsocket_class._create(
    501             sock=sock,

~/.conda/envs/default/lib/python3.9/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040                     self.do_handshake()
   1041             except (OSError, ValueError):

~/.conda/envs/default/lib/python3.9/ssl.py in do_handshake(self, block)
   1308                 self.settimeout(None)
-> 1309             self._sslobj.do_handshake()
   1310         finally:

SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~/.conda/envs/default/lib/python3.9/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    439             if not chunked:
--> 440                 resp = conn.urlopen(
    441                     method=request.method,

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    784 
--> 785             retries = retries.increment(
    786                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

~/.conda/envs/default/lib/python3.9/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    591         if new_retry.is_exhausted():
--> 592             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    593 

MaxRetryError: HTTPSConnectionPool(host='openapi.indiainfoline.com', port=443): Max retries exceeded with url: /VendorsAPI/Service1.svc/JWTOpenApiValidation (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
/tmp/ipykernel_53/3809616873.py in <module>
    510     return
    511 
--> 512 allInOneFunction(client,client2,csv,5)
    513 
    514 count = 0

/tmp/ipykernel_53/3809616873.py in allInOneFunction(client, client2, csv, timeframe)
    466     from datetime import datetime
    467     import pytz
--> 468     CEPEs = BankNiftyLtp(client,timeframe)
    469     CEPE = CEPEs
    470     print(CEPEs.tail(5).to_string())

/tmp/ipykernel_53/3809616873.py in BankNiftyLtp(client, timeframe)
    116     sec = datetime.now().second
    117     #time.sleep(60-sec)
--> 118     df = client.historical_data('N','C',ScriptCode,timeframe,from_date_format,to_date_format)
    119     #print(df)
    120     df['EMA9'] = df.Close.ewm(span =9 ,adjust=False).mean()

~/.conda/envs/default/lib/python3.9/site-packages/py5paisa/py5paisa.py in historical_data(self, Exch, ExchangeSegment, ScripCode, time, From, To)
    402             log_response(e)
    403 
--> 404     def cancel_order(self,exchange:str,exchange_segment:str,exch_order_id:str):
    405         """
    406         Cancels an existing order

~/.conda/envs/default/lib/python3.9/site-packages/py5paisa/py5paisa.py in jwt_validate(self)
    397             self.set_payload(order)
    398             self.payload["body"]["ExchOrderID"] = order.exch_order_id
--> 399 
    400             return self.order_request("OM")
    401         except Exception as e:

~/.conda/envs/default/lib/python3.9/site-packages/requests/sessions.py in post(self, url, data, json, **kwargs)
    575         """
    576 
--> 577         return self.request('POST', url, data=data, json=json, **kwargs)
    578 
    579     def put(self, url, data=None, **kwargs):

~/.conda/envs/default/lib/python3.9/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    527         }
    528         send_kwargs.update(settings)
--> 529         resp = self.send(prep, **send_kwargs)
    530 
    531         return resp

~/.conda/envs/default/lib/python3.9/site-packages/requests/sessions.py in send(self, request, **kwargs)
    643 
    644         # Send the request
--> 645         r = adapter.send(request, **kwargs)
    646 
    647         # Total elapsed time of the request (approximately)

~/.conda/envs/default/lib/python3.9/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    515             if isinstance(e.reason, _SSLError):
    516                 # This branch is for urllib3 v1.22 and later.
--> 517                 raise SSLError(e, request=request)
    518 
    519             raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='openapi.indiainfoline.com', port=443): Max retries exceeded with url: /VendorsAPI/Service1.svc/JWTOpenApiValidation (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)')))

i am getting this error again and again form few day before it not used to come.

**Comment by 5paisa** [comment]
Which function is giving this issue?

**Comment by vinayakbhovi** [comment]
while getting historical data

df=client.historical_data('N','C',1660,'15m','2021-05-25','2021-06-16')
print(df)

**Comment by 5paisa** [comment]
@vinayakbhovi can you check this again?
