### ISSUE TITLE
How to get order status in realtime any thing is there to get realtime order status.

### ISSUE THREAD

**Issue by Sksingh97** [5paisa/py5paisa#159]
I want to get order status in realtime is there any way to achieve this. Either via web-socket/web-hook.

**Comment by 5paisa** [comment]
Yes, we have a websocket for getting order updates.
Check here:- https://invest.5paisa.com/DeveloperAPI/LiveQuotes

(login needed to check this page)

**Comment by karthikdatta** [comment]
The link you have provided is referring to Live Market Streaming. How is it related to Orders?
