### ISSUE TITLE
client.order_book() is not returning the order price

### ISSUE THREAD

**Issue by rajeshbagavathy** [5paisa/py5paisa#163]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description
client.order_book() is not returning the order price in which the trade was executed

### What I Did

I am trying to fetch my order details to put the stop loss, Its returning every other details but not order price details.
I also tried using client.positions(), but the problem is it doesn't have the tag field, so i couldn't filter my trade based on the tag.

Could you please help me if there is any other way of getting order price.

code:
orders = client.order_book()

**Comment by 5paisa** [comment]
Use RemoteorderID as tag and hit OrderStatus to get price
