### ISSUE TITLE
Error in place_order

### ISSUE THREAD

**Issue by vspl-girish** [5paisa/py5paisa#164]
* 5paisa Python SDK version: current master branch
* Python version: 3.8.10
* Operating System: Ubuntu/Linux 20.04

### Description

Trying to place order after successful login

### What I Did
Ran your sample code from README

test_order = Order(order_type='B',exchange='N',exchange_segment='C', scrip_code = 1660, quantity=1, price=236.5,is_intraday=True,remote_order_id="tag")
client.place_order(test_order)

I get the following error:
```
[Errno Unexpected UTF-8 BOM (decode using utf-8-sig)] ﻿<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Request Error</title>
    <style>...</style>
  </head>
  <body>
    <div id="content">
      <p class="heading1">Request Error</p>
      <p>The server encountered an error processing the request. See server logs for more details.</p>
    </div>
  </body>
</html>
```

**Comment by vspl-girish** [comment]
Is anyone able to successfully place orders? Please give me some sample code that works

**Comment by 5paisa** [comment]
Please verify if you were logged in and followed all steps above
