### ISSUE TITLE
Not able to Login to API getting : 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by srivatsa-bc** [5paisa/py5paisa#165]
* 5paisa Python SDK version: 0.4.8
* Python version: 3.9
* Operating System: Windows

Not able to login to the API

Is there any other way to login

from py5paisa import FivePaisaClient
used this code:
cred={
    "APP_NAME":"#######",
    "APP_SOURCE":"#######",
    "USER_ID":"#######",
    "PASSWORD":"#######",
    "USER_KEY":"#######",
    "ENCRYPTION_KEY":#######"
    }

client = FivePaisaClient(email=email, passwd=passwd, dob=dob, cred=cred)
client.login()

output:

'NoneType' object is not subscriptable

**Comment by rsmahanti** [comment]
I am facing same issue. Some time it works, some time it don't.

**Comment by 5paisa** [comment]
Please be updated to the latest python package of py5paisa
