### ISSUE TITLE
Why is fetch_market_feed is much slower than fetch_market_depth_by_symbol?

### ISSUE THREAD

**Issue by balavram** [5paisa/py5paisa#166]
* 5paisa Python SDK version: 0.4.8
* Python version: 3.10.2
* Operating System: Windows 10 Pro

### Description

I expected it to be other way, as per the documentation fetch_market_feed is compact market snapshot and fetch_market_depth_by_symbol is full market snapshot.

### What I Did

NIFTY, Expiry : 12 May 2022, Strikes : 16700, 16800, 16900, 17000, 17100 , Option_type (PE, CE)

I timed both calls with the same 10 NIFTY option symbols and timings are

1.8605470657348633 vs 0.5927307605743408

**Comment by 5paisa** [comment]
We can improve this !
Thanks for feedback
