### ISSUE TITLE
Unable to place order in Bank nifty option using the scripdata

### ISSUE THREAD

**Issue by kumarchinmaya116** [5paisa/py5paisa#167]
* 5paisa Python SDK version: 0.3.6
* Python version: 3.9.7
* Operating System: windows 10

### Description

I am unable to place order in bank nifty option using the scrip data. It only accepts the scrip code method. However, the scrip master csv available in the official website is not updated regularly (bank nifty weekly expiry options data for 19th may 2022 has not been updated as on 13-05-2022, 09:45 am)

#Using Scrip Data :-

```
test_order = Order(order_type='B',exchange='M',exchange_segment='D', scripdata = 'GOLDM 03 Nov 2021_20211103', quantity=1, price=47900,is_intraday=True,IsGTCOrder=False,IsEOSOrder=True,remote_order_id="tag")
client.place_order(test_order)
```

### What I Did
I tried placing order using scripdata as follows:

```
test_order = Order(order_type='B',exchange='N',exchange_segment='D', scripdata = 'BANKNIFTY 19 May 2022 CE 33700.00', quantity=25, price=0,is_intraday=False)
client.place_order(test_order)
```
However, the order did not go through and I recieved the response text as: 'Invalid ScripData'
Kindly look into the matter

Regards
Chinmaya Kumar Rath
Email: kumarchinmaya116@gmail.com

**Comment by 5paisa** [comment]
Hi @kumarchinmaya116 ,

For options scripdata passed should be as below:-
Example:- Options scrip : "NIFTY 30 Sep 2021 CE 11000.00_20210930_CE_11000" (symbol,expiry, call/put, strikerate) for currency and commodity same pattern will be followed.

**Comment by root-demons** [comment]
The same happend to me, the reason is there is no data for Banknifty options of 19 May expiry in scripmaster file.

**Comment by fannnu** [comment]
I'm facing the same issue. No data for BNF 19 May expiry, while there is data for 26 May (monthly) expiry.  Thus, I'm forced to use the latter expiry.

**Comment by kumarchinmaya116** [comment]
Hi @5paisa ,
Thank you for the quick response. However I figured out I can extract the scrip code from the market feed also. This solved my problem.
