### ISSUE TITLE
SL order not working

### ISSUE THREAD

**Issue by rakesh146** [5paisa/py5paisa#17]
Stoploss order for derivatives are not working. Getting rejected by exachange.![Screenshot_20200922-155130.jpg](https://user-images.githubusercontent.com/64532161/93870944-8bbaa300-fceb-11ea-914e-4945634df71b.jpg)

**Comment by invinciblycool** [comment]
Was this placed using the Python SDK?

**Comment by rakesh146** [comment]
Yes

**Comment by rakesh146** [comment]
Python gives a success response but in terminal,it's failing

**Comment by rakesh146** [comment]
Any chance to check on it?

**Comment by rrjain1** [comment]
@rakesh146 can you please share the order code for weekly banknifty

**Comment by rakesh146** [comment]
buy_sl_order = Order(order_type=OrderType.BUY, scrip_code=59016, quantity=25,exchange=Exchange.NSE
                  ,exchange_segment=ExchangeSegment.DERIVATIVE,price = 30.0,atmarket=False,
                  is_stoploss_order=True,stoploss_price= 100.0,is_intraday=True,ahplaced = AHPlaced.AFTER_MARKET_CLOSED)
                  
client.place_order(buy_sl_order)

#change the script code as required

**Comment by rakesh146** [comment]
It worked after setting testorder.disqty=0.

Thanks

**Comment by invinciblycool** [comment]
Great! Closing this issue then

**Comment by pushand** [comment]
@rakesh146 @ba11b0y 
I'm sending this in market feed api still not getting zero value in response, basically i want to get scrip code. can you help pointing whats wrong/missing here?

` {
                "Exch": "N",
                "ExchType": "D",
                "Symbol": "BANKNIFTY 21 JUN 2021",
                "Expiry": "20210624",
                "StrikePrice": "35200",
                "OptionType": "CE"
            }`

**Comment by qalpesh** [comment]
symbol should be corrected as follows "Symbol": "BANKNIFTY 21 JUN 2021 CE 35300.00"
