### ISSUE TITLE
Timestamp not available in market depth feed

### ISSUE THREAD

**Issue by Neil-A** [5paisa/py5paisa#174]
{"Exch":"N","ExchType":"C","Token":2475,"TBidQ":1524077,"TOffQ":1434328,"Details":[{"Quantity":827,"Price":150.4,"NumberOfOrders":14,"BbBuySellFlag":66},{"Quantity":5535,"Price":150.35,"NumberOfOrders":18,"BbBuySellFlag":66},{"Quantity":10308,"Price":150.3,"NumberOfOrders":23,"BbBuySellFlag":66},{"Quantity":20314,"Price":150.25,"NumberOfOrders":28,"BbBuySellFlag":66},{"Quantity":15491,"Price":150.2,"NumberOfOrders":28,"BbBuySellFlag":66},{"Quantity":154,"Price":150.45,"NumberOfOrders":1,"BbBuySellFlag":83},{"Quantity":3514,"Price":150.5,"NumberOfOrders":21,"BbBuySellFlag":83},{"Quantity":3280,"Price":150.55,"NumberOfOrders":19,"BbBuySellFlag":83},{"Quantity":16556,"Price":150.6,"NumberOfOrders":31,"BbBuySellFlag":83},{"Quantity":10726,"Price":150.65,"NumberOfOrders":21,"BbBuySellFlag":83}],"TimeStamp":0,"Time":"\/Date(1653552145927)\/"}
```
Timestamp is always shown as 0, How to convert Time format Date(1653552145927) to standard formats?

**Comment by Neil-A** [comment]
Thanks @akshay7892 👍 

Since the datafeed contains the epochtime within a string like: '/Date(1654162842666)/'

I had to use:

**Comment by akshay7892** [comment]
I'm not sure if this one is better but still , suppose you are assigning the market depth which is an dict to variable ```a``` , i.e. ```a ={market depth values}```. Then we know could access the ```"Time":"/Date(1653552145927)/"``` part as ```a['Time']``` which would get us ```/Date(1653552145927)/``` . Now we could use ```replace``` method to extract the epoch value. Which then we can use to convert in any form we want. e.g.
```
human_time = (time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(int(str(a['Time'].replace('/Date(','').replace(')/',''))))))

```
Hope this helps

**Comment by Neil-A** [comment]
Thank you! @akshay7892

**Comment by akshay7892** [comment]
I dont know about the feed but websocket market depth feed, but response from websocket isn't a valid python dict so you should use ```json.loads(message)``` to make it python dict.
