### ISSUE TITLE
SlopLoss order is giving error

### ISSUE THREAD

**Issue by prakhar9837** [5paisa/py5paisa#177]
### Description
Stoploss Order is getting rejected from Exchange. The error from Exchange shown in UI is "Invalid Combination Of mf/aon/disclosed volume".
The reason is same value what we are passing in quantity is passed to DisclosedQty also and in turn giving error.
Please allow us to pass disclosedQty also in Constructor or fix this issue from 5paisa API order or also from 5paisa manual order.
This issue is there in 5paisa mobile app also when we are trying to place a stoploss order with disclosed Qty.

### What I Did

```
test_order = Order(order_type='S',exchange='N',exchange_segment='D', scrip_code = 55727, quantity=50, price=10, stoploss_price = 10.05, is_stoploss_order = True ,is_intraday=False, remote_order_id="Order1")
order_status = client.place_order(test_order)
```

**Comment by 5paisa** [comment]
Seems you are trying to place a bracket order. Please use bo_co_order() to place such orders successfully.

**Comment by prakhar9837** [comment]
I don't think placing stoploss order is possible using bo_co_order().
As per the APIs provided by you placing stoploss is possible using Order() only, which is giving error.

Please check. As per the existing code there is no way to place stoploss order by using any of your APIs.
I made changes in my local and I was able to place SL orders using Order()
