### ISSUE TITLE
Order_id

### ISSUE THREAD

**Issue by rakesh146** [5paisa/py5paisa#18]
How to get the order I'd of a order placed.. couldn't find anywhere as response

**Comment by rakesh146** [comment]
Hi @invinciblycool ,

Please add below line inside order_request()

return res["body"]

#This will help to get order id when we place a order

**Comment by rishabhmaniyar** [comment]
Hey @rakesh146 ,

you will not get exchange order id from in response from order request api.
You can hit tradebook to get trade related information.
