### ISSUE TITLE
Trade station UI MTM is not matching with client.positions() response

### ISSUE THREAD

**Issue by rajeshbagavathy** [5paisa/py5paisa#180]
* 5paisa Python SDK version: 
* Python version: 2.7
* Operating System: Mac os

### Description
MTM amount is matching with UI:

### What I Did
I have been using client.positions to get MTM amount for my existing position.
When i compare the Mtm amount of api vs UI, its completely different. I compared scrip name its everything is matching. But the mtm amount is totally different. Due to this I am getting too much difference in price.

**Comment by 5paisa** [comment]
MTM amount also discounts BookedPL and in tradestation it shows combined.

Please take sum of both when comparing the 2 MTM values
