### ISSUE TITLE
LOGIN API NOT WORKING

### ISSUE THREAD

**Issue by amankumarjain** [5paisa/py5paisa#182]
* 5paisa Python SDK version: latest
* Python version: 3.8
* Operating System: Mac

### Login API Response:
{'body': None, 'head': {'responseCode': '5PLoginV4', 'status': '2', 'statusDescription': 'Invalid head parameters.'}}

### Login Payload Hardcoded in Code:
LOGIN_PAYLOAD = {"head": {
    "appName": "",
    "appVer": "1.0",
    "key": "",
    "osName": "WEB",
    "requestCode": "5PLoginV2",
    "userId": "",
    "password": ""
},
    "body":
    {
    "Email_id": "",
    "Password": "",
    "LocalIP": "192.168.10.10",
    "PublicIP": "192.168.10.10",
    "HDSerailNumber": "",
    "MACAddress": "",
    "MachineID": "039377",
    "VersionNo": "1.7",
    "RequestNo": "1",
    "My2PIN": "",
    "ConnectionType": "1"
}}

what is invalid head parameter in this

### What I Did

what kind of sdk you guys are hosting, even login api is not working, everything is hardcoded in your code and only 
appName, key, userId, password is variable.
all these variables are provided in code still is is not working. 

get rid of your developers and hire new people.

**Comment by 5paisa** [comment]
Please upgrade your package to latest version current one you are using is old version.
