### ISSUE TITLE
Incorrect OI data, BNF option chain

### ISSUE THREAD

**Issue by fannnu** [5paisa/py5paisa#185]
* 5paisa Python SDK version: Latest one
* Python version: 3.9
* Operating System: Windows 10

### Description

While trying to fetch the option chain for BANKNIFTY, the data which is coming seems incorrect while trying to match it with OI data shown on the NSE site and other option chain providers. 

- Also the way through which we have to specify expiry seems bulky. I'm sure a more straightforward process to get the option chain by having the expiry date as input would suffice.

**Comment by 5paisa** [comment]
Please give the instance of mis-match on our mail (support@5paisa.com)
