### ISSUE TITLE
Error while fetching trade info and order status

### ISSUE THREAD

**Issue by rakesh146** [5paisa/py5paisa#19]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description
Error while fetching trade info and order status

Throwing error --> Object of type Exchange is not JSON serializable

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
from py5paisa.order import OrderForStatus, Exchange, RequestList
test_order_status = OrderForStatus(exchange=Exchange.BSE, exchange_segment=ExchangeSegment.CASH, scrip_code=890147, order_id=0)
req_list = RequestList()
# Add multiple orders to the RequestList to know status of multiple orders at once.
req_list.add_order(test_order_status)

client.fetch_order_status(req_list)
client.fetch_trade_info(req_list)

**Comment by rrjain1** [comment]
If I run the same code, getting below error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from py5paisa.order import OrderForStatus, Exchange, ExchangeType, RequestList
ImportError: cannot import name 'ExchangeType' from 'py5paisa.order' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\py5paisa\order.py)
```

**Comment by rakesh146** [comment]
@rrjain1 .. try importingg ExchangeSegment

**Comment by tarunw07** [comment]
Hi @rakesh146 I have fixed this issue and opened a pull request. I am not sure how much time will it take to get that pull request approved. Meanwhile if you would like to test it out, please give it a try and let me know if you face any issues. [https://github.com/tarunw07/py5paisa/tree/fixes/fetch_trade_info_and_order_status_fix](url)

**Comment by rakesh146** [comment]
@tarunw07 Great.. thanks

**Comment by rrjain1** [comment]
thanks @rakesh146  it worked after exporting Exchangesegment
