### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by vinayakbhat87** [5paisa/py5paisa#191]
* 5paisa Python SDK version: 0.5.1
* Python version:3.10.5
* Operating System: Windows 10

### Description

login is not working
10:08:19 | 'NoneType' object is not subscriptable
 10:08:19 | 'FivePaisaClient' object has no attribute 'ENCRYPTION_KEY'

### What I Did
I have the keys.conf file and it has encryption key value as well
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by AlwiLion** [comment]
tried with new method by its still give error

```
cred={
    "APP_NAME":"***",
    "APP_SOURCE":"**",
    "USER_ID":"***",
    "PASSWORD":"***",
    "USER_KEY":"**",
    "ENCRYPTION_KEY":"**"
    }
client = FivePaisaClient(email="**@gmail.com", passwd="**", dob="**",cred=cred)
client.login()
```
getting below error

 11:53:48 | 'NoneType' object is not subscriptable
 11:53:48 | 'NoneType' object is not subscriptable
