### ISSUE TITLE
Issue While Placing Fresh Order through Latest Python SDK version

### ISSUE THREAD

**Issue by vmachs** [5paisa/py5paisa#195]
* 5paisa Python SDK version: v0.5.1-pre-alpha Latest
* Python version: Python 3.6 (Google Colab)
* Operating System: Windows 11 (Browser Google Chrome)

### Description
Below given Error coming While Placing the Fresh Order
**"TypeError: place_order() takes 1 positional argument but 2 were given"**

Infosys Ltd Script Code (1594) from NSE Exchange Selected for test purpose..

Error Image Attached for Ref.
![image](https://user-images.githubusercontent.com/71798797/178012154-1c1b115a-cbe8-4563-b27e-5fa2cfc16363.png)

Kindly guide me or share the help document, if i am not given correct parameters or any mandatory details missed out while placing order through SDK.

**Comment by nageshraj** [comment]
Hey, I am facing the same issue too

**Comment by 5paisa** [comment]
Please use updated syntax now! We have changed it @vmachs

**Comment by vmachs** [comment]
@5paisa  Thanks... Issue Resolved...

**Comment by dineshiitd** [comment]
> @5paisa Thanks... Issue Resolved...

hi can you plz type the new syntax.
