### ISSUE TITLE
What is the correct way to login

### ISSUE THREAD

**Issue by mr-easy** [5paisa/py5paisa#200]
In the documentation, it says that the KEYS.CONF way of login is removed, but when trying to log in using:
```
from py5paisa import FivePaisaClient  
client = FivePaisaClient(email=cred['user'], passwd=cred['pass'], dob=cred['dob'], cred=cred)  
client.login()
```
I get the Exception:
`Exception: Please configure your keys in keys.conf`

**Comment by AlwiLion** [comment]
Hello 

Am also facing an issue with login I am trying to login with below code

```
cred={
    "APP_NAME":"***",
    "APP_SOURCE":"**",
    "USER_ID":"***",
    "PASSWORD":"***",
    "USER_KEY":"**",
    "ENCRYPTION_KEY":"**"
    }
client = FivePaisaClient(email="**@gmail.com", passwd="**", dob="**",cred=cred)
client.login()
```
getting this error 

 11:53:48 | 'NoneType' object is not subscriptable
 11:53:48 | 'NoneType' object is not subscriptable
