### ISSUE TITLE
API authentication failed

### ISSUE THREAD

**Issue by JunaidAfr** [5paisa/py5paisa#203]
* 5paisa Python SDK version:0.5.4
* Python version:3.10.6
* Operating System: Windows

### Description

Authentication was working well till Friday. Afterward, it has been showing this error.

[32m 09:19:05[0m | [1mInvalid Input Parameters.[0m

What is the problem here?

**Comment by fannnu** [comment]
> Probably Python 3.10. Try with 3.9.

I'm getting the same error with Python 3.7.12 . Such auth errors ruin the entire trading day

**Comment by SomaKonijeti** [comment]
Yeah. 5paisa team is totally irresponsible and inactive. There is no support team for APIs

**Comment by JunaidAfr** [comment]
Now getting different error message.
�[32m 14:34:50�[0m | �[1m'body'�[0m
�[32m 14:34:50�[0m | �[1m'NoneType' object is not subscriptable�[0
