### ISSUE TITLE
Cancel order and Modify order do not work

### ISSUE THREAD

**Issue by rakesh146** [5paisa/py5paisa#21]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description
Cancel order and Modify order do not work and throw a error

```
Code:
client.cancel_order(exch_order_id=320007170, traded_qty=1, scrip_code=890147)
```

Error: Client handler to Exchange Connector connection stopped',

**Comment by rakesh146** [comment]
It's working now after few modifications

**Comment by rakesh146** [comment]
I have created order separately for modify n cancel as we do for order placement

**Comment by rrjain1** [comment]
@rakesh146 if u don't mind can u please share the code.. I'm struggling for almost a month to get this worked... it was quiet easy for me to get the coding done for zerodha.. somehow I'm not able to achieve the same result with 5paisa api

**Comment by rakesh146** [comment]
@rrjain1 ..sure..will do tomo

**Comment by rrjain1** [comment]
Thanks @rakesh146 , what I need is how we can read Pending orders (Stoploss orders). What I want to achieve is to cancel the pending order via api before exitting the open positions.

**Comment by rakesh146** [comment]
@rrjain1 ..Okay..First thing first..I m no expert but tried hard to get it resolved. And I have written algos for upstox,alice n 5paisa and using 5paisa bcz of low brokerage..thanks to its subscription plan.
Second thing..my approach is a bit lengthier but it solves my purpose and I hope, it will solve urs too.

Approach begins here:
step-1:
Extract 5paisa.py file from attached folder and replace it with ur 5paisa.py file inside Lib\site-packages\py5paisa folder. It has three modifications:
a. It returns response data after placing any order
b. Changes in modify_order
c. Changes in cancel_order
[5paisa.zip](https://github.com/5paisa/py5paisa/files/5344636/5paisa.zip)

Step-2:
a. login ur 5paisa in any editor of ur choice.
b. from py5paisa.order import Order, OrderType,Exchange,ExchangeSegment,AHPlaced,OrderFor
c. Place a SL order:

buy_sl_pe_order = Order(order_type=OrderType.BUY, scrip_code=37282, quantity=25,exchange=Exchange.NSE
                  ,exchange_segment=ExchangeSegment.DERIVATIVE,is_stoploss_order=True,atmarket=False,price = 
                  85.0,stoploss_price=80.0,is_intraday= True)

buy_sl_pe_order.disqty = 0

ret_buy_sl_pe_order = client.place_order(buy_sl_pe_order)

You will get below response:

{'BrokerOrderID': 320574467,
 'ClientCode': '51590681',
 'Exch': 'N',
 'ExchOrderID': '',
 'ExchType': 'D',
 'LocalOrderID': 0,
 'Message': 'Success',
 'RMSResponseCode': 0,
 'ScripCode': 37282,
 'Status': 0,
 'Time': '/Date(1601836200000+0530)/'}

Noe: Here,we received exchange id as 0 which is necessary for order modification and cancelation.

Srep-3:
get exchange id using broker id. use below code:
def get_exchange_order_id(broker_id):
    exch_id = 0
    for orders in client.order_book():
        if orders['BrokerOrderId'] == broker_id:
            exch_id = orders['ExchOrderID']
    return exch_id

Step-4:
Create order for order modification.
mod_order = Order(order_type=OrderType.BUY, 
                                scrip_code=37318,quantity=25,order_for=OrderFor.MODIFY,exchange=Exchange.NSE,
                                exchange_segment=ExchangeSegment.DERIVATIVE,is_stoploss_order=True,atmarket=False,
                                price=220.00,stoploss_price=240.00,exch_order_id=1400000057004454,is_intraday= True)

mod_order.disqty = 0 

modify_my_sl_order = client.modify_order(mod_order)

You will get below responce:
'BrokerOrderID': 321221659,
 'ClientCode': '51590681',
 'Exch': 'N',
 'ExchOrderID': '',
 'ExchType': 'D',
 'LocalOrderID': 0,
 'Message': 'Success',
 'RMSResponseCode': 0,
 'ScripCode': 37318,
 'Status': 0,
 'Time': '/Date(1601922600000+0530)/'}

After that check in your terminal.

Thats All!.You are good to go.

Feel free to give a thumbs up!!

**Comment by rrjain1** [comment]
thanks a lot @rakesh146

**Comment by rrjain1** [comment]
@rakesh146 thanks finally I am able to through with the ordering and modification part, everything is working perfectly fine now... One last help how are you reading the scriptcode from scripmaster available at https://www.5paisa.com/docs/default-source/scrip-master/contract.txt..  For example with the code and logic I am able to derive the strike I need to place order for eg my output from code is in this format: **BANKNIFTY20O0823200PE** , how can I get it's assigned script code i.e. 37325 in fastest way..

**Comment by invinciblycool** [comment]
Thanks @rakesh146  for sharing the info.
@rrjain1 5paisa will soon be changing the APIs so that you don't have to pass in the scrip code anymore.
This is under rapid development, for the time being you could parse the above file and assign scrip code.

**Comment by rakesh146** [comment]
@invinciblycool Thanks a lot
@rrjain1 ..I m using Alice for web socket n other details and placing orders in 5 paisa n Alice both

**Comment by rrjain1** [comment]
@rakesh146 @invinciblycool 

When I try to cancel the pending order, I am getting following error, If I Print the data, the same is matching with the output i am getting.

```
ExchOrderID = int(dfi['ExchOrderID'])
if PendingQty > 0 and Qty > 0 and DelvIntra == "D" and OrderStatus == "AH Placed":          
	client.cancel_order(exch_order_id=ExchOrderID], traded_qty=PendingQty, scrip_code=ScripCode)
```

**`cancel_order() got an unexpected keyword argument 'exch_order_id'
`**

![Error](https://user-images.githubusercontent.com/69988393/95787725-b8187c80-0cf7-11eb-8933-e290ee54fb4b.JPG)

**Comment by rakesh146** [comment]
@rrjain1 Try this.

def cancel_all_pending_orders():
    print('cancel_all_pending_orders')
    for orders in client.order_book():
        if orders['OrderStatus'] in ['Pending','Modified']:
            print(orders['ExchOrderID'])
                mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
                mod_order.disqty = 0
                ret_mod_pe_order = client.modify_order(mod_order)
                print('cancelled orders',ret_mod_pe_order)

**Comment by rakesh146** [comment]
> @rakesh146 @invinciblycool 
> 
> When I try to cancel the pending order, I am getting following error, If I Print the data, the same is matching with the output i am getting.
> 
> **Code**
> ```
> ExchOrderID = int(dfi['ExchOrderID'])
> if PendingQty > 0 and Qty > 0 and DelvIntra == "D" and OrderStatus == "AH Placed":          
> 	client.cancel_order(exch_order_id=ExchOrderID], traded_qty=PendingQty, scrip_code=ScripCode)
> ```
> 
> **Output Error**
> 
> **`cancel_order() got an unexpected keyword argument 'exch_order_id'
> `**
> 
> **Error Screenshot**
> ![Error](https://user-images.githubusercontent.com/69988393/95787725-b8187c80-0cf7-11eb-8933-e290ee54fb4b.JPG)
> 

    @rrjain1 Try this if u have already updated py5paisa.py which I shared on the last comment.

**Code**

def cancel_all_pending_orders():
    print('cancel_all_pending_orders')
    for orders in client.order_book():
        if orders['OrderStatus'] in ['Pending','Modified']:
            print(orders['ExchOrderID'])
                mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
                mod_order.disqty = 0
                ret_mod_pe_order = client.modify_order(mod_order)
                print('cancelled orders',ret_mod_pe_order)

**Comment by rakesh146** [comment]
**code**

def cancel_all_pending_orders():
    print('cancel_all_pending_orders')
    for orders in client.order_book():
        if orders['OrderStatus'] in ['Pending','Modified']:
            print(orders['ExchOrderID'])
            if orders['ExchOrderID'] in ['all_order_id_ce[-1]','all_order_id_pe[-1]']:
                mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
                mod_order.disqty = 0
                ret_mod_pe_order = client.modify_order(mod_order)
                print('cancelled orders',ret_mod_pe_order)

**Comment by rakesh146** [comment]
Hi


def cancel_all_pending_orders():
    print('cancel_all_pending_orders')
    for orders in client.order_book():
        if orders['OrderStatus'] in ['Pending','Modified']:
            print(orders['ExchOrderID'])
            if orders['ExchOrderID'] in ['all_order_id_ce[-1]','all_order_id_pe[-1]']:
                mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
                mod_order.disqty = 0
                ret_mod_pe_order = client.modify_order(mod_order)
                print('cancelled orders',ret_mod_pe_order)
**Code**

**Comment by rakesh146** [comment]
> @rakesh146 @invinciblycool 
> 
> When I try to cancel the pending order, I am getting following error, If I Print the data, the same is matching with the output i am getting.
> 
> **Code**
> ```
> ExchOrderID = int(dfi['ExchOrderID'])
> if PendingQty > 0 and Qty > 0 and DelvIntra == "D" and OrderStatus == "AH Placed":          
> 	client.cancel_order(exch_order_id=ExchOrderID], traded_qty=PendingQty, scrip_code=ScripCode)
> ```
> 
> **Output Error**
> 
> **`cancel_order() got an unexpected keyword argument 'exch_order_id'
> `**
> 
> **Error Screenshot**
> ![Error](https://user-images.githubusercontent.com/69988393/95787725-b8187c80-0cf7-11eb-8933-e290ee54fb4b.JPG)
> 


def cancel_all_pending_orders():
    print('cancel_all_pending_orders')
    for orders in client.order_book():
        if orders['OrderStatus'] in ['Pending','Modified']:
            print(orders['ExchOrderID']:
                mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
                mod_order.disqty = 0
                ret_mod_pe_order = client.modify_order(mod_order)
                print('cancelled orders',ret_mod_pe_order)

**Comment by rakesh146** [comment]
@rrjain1 .If u have already replaced py5paisa.py with the one I shared on my last comment then try this.

> **Code


def cancel_all_pending_orders():
    print('cancel_all_pending_orders')
    for orders in client.order_book():
        if orders['OrderStatus'] in ['Pending','Modified']:
            print(orders['ExchOrderID'])
                mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
                mod_order.disqty = 0
                ret_mod_pe_order = client.modify_order(mod_order)
                print('cancelled orders',ret_mod_pe_order)

**Comment by rakesh146** [comment]
@rrjain1 Above code is to cancel a SL buy pending order

**Comment by rrjain1** [comment]
@rakesh146  thanks a lot...
Will check in live market tomorrow, somehow I am not able to  get this work for offline orders placed as "AH Placed"

**Comment by rakesh146** [comment]
@rrjain1 remove isintraday=True

**Comment by rakesh146** [comment]
@rrjain1 keep AH placed bcz now status is AH placed

**Comment by rrjain1** [comment]
@rakesh146 yeah but that is throwing the error .. may be @invinciblycool can guide what is causing this error... and how this can be resolved

**Comment by rrjain1** [comment]
@rakesh146 getting same error for even pending order...

cancel_all_pending_orders
1602646200001420621
Traceback (most recent call last):
  File "test.py", line 214, in <module>
    mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.BSE, exchange_segment=ExchangeSegment.CASH,price=0.0,exch_order_id=orders['ExchOrderID'])
AttributeError: 'str' object has no attribute 'CANCEL'

**Comment by rakesh146** [comment]
> @rakesh146 getting same error for even pending order...
> 
> **This is the ouput for the order that i want to cancel...**
> 
> {'AHProcess': 'N', 'AfterHours': 'N', 'AtMarket': 'N', 'BrokerOrderId': 325375751, 'BrokerOrderTime': '/Date(1602652328023+0530)/', 'BuySell': 'B', 'DelvIntra': 'D', 'DisClosedQty': 0, 'Exch': 'B', 'ExchOrderID': '1602646200001420621', 'ExchOrderTime': '/Date(1602652327000+0530)/', 'ExchType': 'C', 'MarketLot': 20, 'OldorderQty': 0, 'OrderRequesterCode': '54544140 ', 'OrderStatus': 'Pending', 'OrderValidUpto': '14 Oct 2020', 'OrderValidity': 0, 'PendingQty': 20, 'Qty': 20, 'Rate': 260, 'Reason': '', 'RequestType': 'P', 'SLTriggerRate': 0, 'SLTriggered': 'N', 'SMOProfitRate': 0, 'SMOSLLimitRate': 0, 'SMOSLTriggerRate': 0, 'SMOTrailingSL': 0, 'ScripCode': 532626, 'ScripName': 'PONDYOXIDE', 'TerminalId': 204, 'TradedQty': 0, 'WithSL': 'N'}
> 
> **Error Message**
> 
> cancel_all_pending_orders
> 1602646200001420621
> Traceback (most recent call last):
> File "test.py", line 214, in
> mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.BSE, exchange_segment=ExchangeSegment.CASH,price=0.0,exch_order_id=orders['ExchOrderID'])
> AttributeError: 'str' object has no attribute 'CANCEL'

@rrjain1 I have just tested and it has worked.

**code
from py5paisa.order import Order, OrderType,Exchange,ExchangeSegment,AHPlaced,OrderFor

for orders in client.order_book():
    if orders['OrderStatus'] in ['Pending','Modified']:
        print(orders['ExchOrderID'])
       
        mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
        mod_order.disqty = 0
        ret_mod_pe_order = client.modify_order(mod_order)
        print(ret_mod_pe_order)
            for orders in client.order_book():
    if orders['OrderStatus'] in ['Pending','Modified']:
        print(orders['ExchOrderID'])
       
        mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
        mod_order.disqty = 0
        ret_mod_pe_order = client.modify_order(mod_order)
        print(ret_mod_pe_order)

**Comment by rakesh146** [comment]
> @rakesh146 getting same error for even pending order...
> 
> **This is the ouput for the order that i want to cancel...**
> 
> {'AHProcess': 'N', 'AfterHours': 'N', 'AtMarket': 'N', 'BrokerOrderId': 325375751, 'BrokerOrderTime': '/Date(1602652328023+0530)/', 'BuySell': 'B', 'DelvIntra': 'D', 'DisClosedQty': 0, 'Exch': 'B', 'ExchOrderID': '1602646200001420621', 'ExchOrderTime': '/Date(1602652327000+0530)/', 'ExchType': 'C', 'MarketLot': 20, 'OldorderQty': 0, 'OrderRequesterCode': '54544140 ', 'OrderStatus': 'Pending', 'OrderValidUpto': '14 Oct 2020', 'OrderValidity': 0, 'PendingQty': 20, 'Qty': 20, 'Rate': 260, 'Reason': '', 'RequestType': 'P', 'SLTriggerRate': 0, 'SLTriggered': 'N', 'SMOProfitRate': 0, 'SMOSLLimitRate': 0, 'SMOSLTriggerRate': 0, 'SMOTrailingSL': 0, 'ScripCode': 532626, 'ScripName': 'PONDYOXIDE', 'TerminalId': 204, 'TradedQty': 0, 'WithSL': 'N'}
> 
> **Error Message**
> 
> cancel_all_pending_orders
> 1602646200001420621
> Traceback (most recent call last):
> File "test.py", line 214, in
> mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.BSE, exchange_segment=ExchangeSegment.CASH,price=0.0,exch_order_id=orders['ExchOrderID'])
> AttributeError: 'str' object has no attribute 'CANCEL'

@rrjain1 I have just tested and it worked.

* *code
from py5paisa.order import Order, OrderType,Exchange,ExchangeSegment,AHPlaced,OrderFor
for orders in client.order_book():
    if orders['OrderStatus'] in ['Pending','Modified']:
        print(orders['ExchOrderID'])
       
        mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE,
                      exchange_segment=ExchangeSegment.DERIVATIVE,price=0.0,exch_order_id=orders['ExchOrderID'],is_intraday= True)
                      #,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)
        mod_order.disqty = 0
        ret_mod_pe_order = client.modify_order(mod_order)
        print(ret_mod_pe_order)

**Comment by rrjain1** [comment]
Thanks @rakesh146 finally I managed to get this work after changing below..

`mod_order = Order(order_type=OrderType.BUY, scrip_code=orders['ScripCode'],quantity=orders['PendingQty'],order_for=OrderFor.CANCEL,exchange=Exchange.NSE, exchange_segment=ExchangeSegment.DERIVATIVE,**price=orders['Rate']**,exch_order_id=orders['ExchOrderID'],**atmarket=False,is_intraday= False,ahplaced= AHPlaced.AFTER_MARKET_CLOSED)**`

Thanks a lot once again for your support...

**Comment by rakesh146** [comment]
@rrjain1 .. welcome dude

**Comment by rakesh146** [comment]
@rrjain1 BTW.. my twitter handle is 
Check out Rksh (@Rksh_rk): https://twitter.com/Rksh_rk?s=08

U can checkout my algo's performance

**Comment by rrjain1** [comment]
> @rrjain1 BTW.. my twitter handle is
> Check out Rksh (@Rksh_rk): https://twitter.com/Rksh_rk?s=08
> 
> U can checkout my algo's performance

sure @rakesh146 will check...

**Comment by rishabhmaniyar** [comment]
Hey @rakesh146 can you close this issue?
