### ISSUE TITLE
historical data JWT error

### ISSUE THREAD

**Issue by karthik6304** [5paisa/py5paisa#232]
* 5paisa Python SDK version:
* Python version:
* Operating System:

Description

Trying to get historical data of bank nifty. The code throws an error 'Invalid JWT.'

What I Did
I tried to run the below code:

bank_nifty_data=client.historical_data('N','C',999920005,'1m','2023-02-14','2023-02-16')

output: 14:52:12 | Expecting value: line 1 column 1 (char 0)
'Invalid JWT.'

<img width="1343" alt="Screenshot 2023-02-27 at 3 02 57 PM" src="https://user-images.githubusercontent.com/97365130/221599653-f12ec6b7-3522-4695-94b9-1039b37ed54c.png">

**Comment by nipunjambaulikar** [comment]
Hi @karthik6304 , I am facing the same issue. Any solution to that ?

**Comment by karthik6304** [comment]
Hello,

Yes, upgrade or reinstall py5paisa library.

 Thankyou
Karthik Ningala
