### ISSUE TITLE
Options trading

### ISSUE THREAD

**Issue by srikanthbojja** [5paisa/py5paisa#28]
is it possible to place buy/sell orders in Options using this API?

**Comment by FeurialBlack** [comment]
> is it possible to place buy/sell orders in Options using this API?

seems like it is possible.

**Comment by srikanthbojja** [comment]
@FeurialBlack do you have any example code?

**Comment by FeurialBlack** [comment]
> @FeurialBlack do you have any example code?

https://github.com/PyPatel/Options-Trading-Strategies-in-Python

**Comment by srikanthbojja** [comment]
@FeurialBlack sorry for the confusion. Now i understand that made my question vague.

I am looking for a code snippet in python for placing buy/sell order for options in python using 5paisa api

@FeurialBlack by the way also thanks for the trading strategy reference

**Comment by shalabhgoel13** [comment]
@srikanthbojja , could you make the python code for getting live marketfeed? I can see that you have asked the question in that thread. Sorry for asking here

**Comment by rishabhmaniyar** [comment]
Hey @srikanthbojja 
Check below snippet for placing order in dervativr segment
```
test_order = Order(order_type=OrderType.BUY, scrip_code='43853', exchange_segment=ExchangeSegment.DERIVATIVE, quantity=75)
client.place_order(test_order)
```

**Comment by rishabhmaniyar** [comment]
We are 

> @srikanthbojja , could you make the python code for getting live marketfeed? I can see that you have asked the question in that thread. Sorry for asking here

We are working on a python version update and have already worked on adding market feed api to sdk.
Soon will update.

Regards
