### ISSUE TITLE
Exchange and exchange types

### ISSUE THREAD

**Issue by shalabhgoel13** [5paisa/py5paisa#29]
Is there a help which tells what the values for the following parameters?

For example, to get marketfeed. The following options needed to be sent. What are the options for each and what do they mean?

1. Expiry
2. StrikePrice 
3. OptionType

**Comment by rishabhmaniyar** [comment]
Hey @shalabhgoel13 
Also sharing a reference example for the Symbol which we request market feed api follow this format strictly.
**### "Symbol":"NIFTY 01 APR 2021 CE 15000.00"**
Expiry is the date stamp of a particular contract expiry ( eg :- 20210401)
StrikePrice is any strike option data you are fetching (eg :- 15000) for NIFTY
OptionType is either CE (Call) PE (Put) (eg:- CE)

PS:- ExchType is ("D") for derivative and "C" for Cash Segment
Regards.
