### ISSUE TITLE
Error while logging in

### ISSUE THREAD

**Issue by kiruthemes** [5paisa/py5paisa#3]
* 5paisa Python SDK version:
* Python version:3.8
* Operating System:Mac OS

Getting the below error while attempting to login

File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py5paisa/py5paisa.py", line 51, in login
    message = res["body"]["Message"]
TypeError: 'NoneType' object is not subscriptable

**Comment by invinciblycool** [comment]
Hey @kiruthemes 
Thanks for your interest in the SDK. The SDK has been tested and it seems to work for me.
A couple of things you might want to check are:

- Make sure you don't enclose your keys in `keys.conf` in quotation marks. Below is a sample.
```
[KEYS]
APP_NAME=YOUR_APP_NAME_HERE
APP_SOURCE=YOUR_APP_SOURCE_HERE
USER_ID=YOUR_USER_ID_HERE
PASSWORD=YOUR_PASSWORD_HERE
USER_KEY=YOUR_USER_KEY_HERE
ENCRYPTION_KEY=YOUR_ENCRYPTION_KEY_HERE
```
- Also, make sure you enter your Date of Birth in `YYYYMMDD` format

```py
from py5paisa import FivePaisaClient

client = FivePaisaClient(email="random_email@xyz.com", passwd="password", dob="YYYYMMDD")
client.login()
```

The authentication flow is given at https://5paisa.github.io/usage/auth/ and you can get your API keys from https://www.5paisa.com/developerapi/apikeys

Feel free to reach out in case you face any further problem 👍

**Comment by kiruthemes** [comment]
Thanks for your reply! I could login now without making any changes. I guess the backend system could be under maintenance when I last tried? Now I'm getting similar error when trying to place the order using the example code in documentation. Will this work only during market hours?

Unfortunately, the documentation is pretty thin so I have couple of questions.
1. Can you provide a single file that has the complete code showing placing an order for any valid stock? Do we need to maintain the login code in the same file where we have the code for placing the order? I'm asking this because other brokers are using access code that is valid for 24 hours so we need not login each time before an order is placed. We can simply instantiate the object using the access code which in turn makes placing the order few seconds faster. 

2. Where can I get the list of script codes? I couldn't find it in NSE website. Any direct link would be appreciated.

A complete sample code would be appreciated where I can just edit my credentials and the order parameters

**Comment by kiruthemes** [comment]
I'm still unable to place orders. Below is the error I'm getting.

 01:00:21 | Logged in!!
Traceback (most recent call last):
  File "/Users/work/Documents/5paisa/login.py", line 10, in <module>
    client.place_order(order)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py5paisa/py5paisa.py", line 169, in place_order
    return self.order_request("OP")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py5paisa/py5paisa.py", line 123, in order_request
    log_response(res["body"]["Message"])
TypeError: 'Response' object is not subscriptable
[Finished in 0.8s with exit code 1]

**Comment by invinciblycool** [comment]
Can you please share the code used for placing the order?
No need for sharing the credentials.

**Comment by kiruthemes** [comment]
@invinciblycool  Below is the code..

```
from py5paisa import FivePaisaClient
from py5paisa.order import Order, OrderType, Exchange

client = FivePaisaClient(email = "xxxxxx", passwd = "xxxx", dob = "xxx")
client.login()

order = Order(order_type=OrderType.BUY, scrip_code=1510401, quantity=10, is_intraday=True)
client.place_order(order)
```
I'm getting the same error when calling client.margin()

Calling client.holdings(), client.positions(), client.order_book() is working though

Appreciate your help!

**Comment by invinciblycool** [comment]
Your code looks fine, it's probably because of an invalid scrip code.
We are trying to get a scrip code reference integrated soon, meanwhile you can try https://www.bsesme.com/corpoaratefilings/ScripsList.aspx

**Comment by kiruthemes** [comment]
@invinciblycool I'm getting the same error even when I change the scrip code to 542057 (BCPL from that list). As I mentioned, even the method client.margin() returns with the same error.

Where do I get the scrip code list for NSE?

**Comment by invinciblycool** [comment]
@kiruthemes Can you please check if you are running the latest version of `py5paisa`
Please try running `pip install py5paisa==0.1.4` to get the latest version.
The latest version has these problems fixed.

While for NSE, please give us some time, we'll be releasing a reference very soon!
Thanks!

**Comment by kiruthemes** [comment]
@invinciblycool Thanks, the order seems to be working now after the update but client.margin() is still returning the same error.

**Comment by invinciblycool** [comment]
Seems to work just fine for me. Anyways, I'll check it again.
Also, do check https://5paisa.github.io/usage/place/ 
It contains detailed reference on placing orders.
If you feel, your issue has been resolved, mind closing this issue? Feel free to open an issue again in any case.
Thanks.

**Comment by kiruthemes** [comment]
Sure, I'm closing the issue. Thanks for your help.

Hope all the functionality will be available soon!

**Comment by uberdeveloper** [comment]
Encountered the same error version `pypaisa==0.1.5`

```
~/anaconda3/lib/python3.6/site-packages/py5paisa/py5paisa.py in login(self)
     49         self.payload["head"]["requestCode"] = "5PLoginV2"
     50         res = self._login_request(self.LOGIN_ROUTE)
---> 51         message = res["body"]["Message"]
     52         if message == "":
     53             log_response("Logged in!!")

TypeError: 'NoneType' object is not subscriptable
```

I could login with requests though
```python
req = requests.post(LOGIN_ROUTE,headers=HEADERS,data=json.dumps(payload))
```

APP_NAME=5P59808196

**Comment by rajasekharnerella** [comment]
Getting error when trying to do client.login().
**File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py5paisa/py5paisa.py", line 70, in __init__
    self.APP_SOURCE=cred["APP_SOURCE"]
TypeError: 'NoneType' object is not subscriptable**
Am using MAC Catalina, Python 3.8, py5paisa SDK. kes.conf (format) as below:
[KEYS]
APP_NAME=YOUR_APP_NAME_HERE
APP_SOURCE=YOUR_APP_SOURCE_HERE
USER_ID=YOUR_USER_ID_HERE
PASSWORD=YOUR_PASSWORD_HERE
USER_KEY=YOUR_USER_KEY_HERE
ENCRYPTION_KEY=YOUR_ENCRYPTION_KEY_HERE
This is what I am trying to do. I am using the variables email, pwd, dob for sending the actual values in the prescribed format.
from py5paisa import FivePaisaClient
client = FivePaisaClient(email=email, passwd=pwd, dob=dob)
client.login()

**Comment by jeevanbond1** [comment]
same issue 
![image](https://user-images.githubusercontent.com/19147952/190710189-7577407b-c490-410e-9e79-7846284f74e4.png)

Login Issue: 
00:09:21 | 'NoneType' object is not subscriptable
 00:09:21 | 'FivePaisaClient' object has no attribute 'ENCRYPTION_KEY'

Can anyone Please help me out.
