### ISSUE TITLE
Unable to get Margin through API : "403 : Access denied." 

### ISSUE THREAD

**Issue by Akash141991** [5paisa/py5paisa#30]
* 5paisa : Using APIs only with Ruby
* Operating System: Windows 10

### Description
Using the margin API, I am getting 403 access denied as status Description. Below is the JSON response:
{"body"=>nil, "head"=>{"responseCode"=>"5PMarginV3", "status"=>"-2", "statusDescription"=>"403 : Access denied."}}

### What I Did
Request url: "https://Openapi.5paisa.com/VendorsAPI/Service1.svc/V3/Margin"
Request payload:
```
{:head=>{:appName=>"5PAKASH", :appVer=>"1.0", :key=>"****", :osName=>"WEB", :requestCode=>"5PMarginV3", :userId=>"****", :password=>"****"},
 :body=>{:ClientCode=>"****", :Email_id=>"****", :Password=>"****", :My2PIN=>"****"}}
```

Any suggestions what might be wrong?! Also, I am using ruby for the API calls, and able to get the positions, holdings and other stuff.

**Comment by Akash141991** [comment]
Getting success response now with same request :)

**Comment by coder-amogh** [comment]
> Getting success response now with same request :)

Can you please post the complete code? I'm trying with Python and it doesn't seem to work. I'm getting invalid session with success code as 200. Check this: #33 

It would definitely help us if you post the code. Thanks!

P.S: Where did you get `My2PIN` from? What exactly it is? Is it the Date Of Birth, or CDSL T-PIN?

**Comment by Akash141991** [comment]
Hi @coder-amogh , For using these APIs a session is to be kept alive which is done by cookiecutter in this repo (I guess!!)
For my purpose, in ruby I am using Faraday (https://github.com/lostisland/faraday) library to maintain a session.
Below is the login code:
```
@http = Faraday.new(url: 'https://Openapi.5paisa.com/VendorsAPI/Service1.svc', headers: {'Content-Type' => 'application/json', 'Connection' => 'keep-alive'}) do |builder|
  builder.use :cookie_jar
  builder.adapter Faraday.default_adapter
end
```
then use the @http instance for first login and then other request:
```@http.post(route, @payload.to_json)```

Also, My2PIN is encrypted DOB.

**Comment by coder-amogh** [comment]
Thanks! @Akash141991 

I just tried today as per the docs, and it works without the 2PIN. I think somehow they have changed the server response, so now we can use it as per the docs!
