### ISSUE TITLE
at_market is True by default and doesn't consider passed price

### ISSUE THREAD

**Issue by coder-amogh** [5paisa/py5paisa#32]
* 5paisa Python SDK version: 0.1.6
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Description

`order = Order(order_type = OrderType.BUY, scrip_code = 1333, quantity = 1, price = 1300, exchange = Exchange.NSE, exchange_segment = ExchangeSegment.CASH)`

This just got through and the buy order was placed at market price. The market price attribute is not even written in the documentation I found [here](https://5paisa.github.io/usage/place/).

### What I Did

So finally I had to do this, and then it worked as expected. I sincerely request you to re-check the documentation and update it accordingly.

```
order = Order(order_type = OrderType.BUY, scrip_code = 1333, quantity = 1, price = 1300, exchange = Exchange.NSE, exchange_segment = ExchangeSegment.CASH, atmarket = False)
```

I think the atmarket should be recalculated if the price passed in is 0 (market order) otherwise it should be False.

**Comment by prateekjjw001** [comment]
yes I also faced this bug, and I had to explicitly pass atmarket=False even with limit orders

**Comment by coder-amogh** [comment]
Seems this issue has been fixed now. I'm closing it.
