### ISSUE TITLE
Fetching Account Balance - Feature Request

### ISSUE THREAD

**Issue by coder-amogh** [5paisa/py5paisa#33]
### Description

I don't see any option to fetch the account balance after the `client.login()` method. The docs say you can get the holdings, order book, margins and positions. There's no option of account balance. Is it possible to add it? Something like: `client.balance()`

Thank you for such wonderful API!

**Comment by coder-amogh** [comment]
I just saw that `client.margin()` should work according to the docs. But, it's not really working. When I try in Python I get NoneType object is not subscriptable. And I didn't have any luck proceeding with normal HTTP request. Any idea why it's not working?

### Here's the code

```
import requests

url = "https://Openapi.5paisa.com/VendorsAPI/Service1.svc/V3/Margin"

data = {
	"head": {
		"appName": "5P52xxxxxx",
		"appVer": "1.0",
		"key": "xxxxxxx",
		"osName": "Android",
		"requestCode": "5PMarginV3",
		"userId": "xxxxxx",
		"password": "xxxxxxx"
	},
	"body": {
		"ClientCode": "52xxxxxx"
	}
}

headers = {
	"Content-Type": "application/json"
}

r = requests.post(url, json = data)

print(r.status_code)

print(r.json())
```

### I get this:

`200`

```{'body': {'ClientCode': '52xxxxxx', 'EquityMargin': [], 'Message': 'Invalid Session', 'Status': 9, 'TimeStamp': '/Date(1607779798712+0530)/'}, 'head': {'responseCode': '5PMarginV3', 'status': '0', 'statusDescription': 'Success'}}```

Anybody can help me, please?

**Comment by shalabhgoel13** [comment]
yes the 5paisa support for api is really pathetic. The request seems to be going properly. I do not know how to make it work. I had also tried it and then gave up. you may try to escalate your issue in 5paisa support

**Comment by coder-amogh** [comment]
@shalabhgoel13 This guy also had the same issue, but somehow he's successful with it... Check this: #30 
Let's see, I'm mailing support. At least proper tests should have been written, so they understand it that it's not working...

**Comment by coder-amogh** [comment]
Cool! 
Somehow it looks like it's working now. (Or maybe because it's not market hours?) But anyway, I think it would also work during market hours, I'm closing the issue. `client.margin()` works perfectly.
