### ISSUE TITLE
Scrip codes for Options

### ISSUE THREAD

**Issue by raj-adroit** [5paisa/py5paisa#36]
Where can i find script codes for Options

**Comment by rishabhmaniyar** [comment]
Hey @raj-adroit you can find that in Market Feeds section until we get in inside the sdk for ease of use.

Regards Rishabh

**Comment by niranjan92** [comment]
@rishabhmaniyar please update the scrip codes file given here - https://www.5paisa.com/docs/default-source/scrip-master/contract.txt or

 **Post a scrip codes files here on Github** 

stuck on this issue since many days. Didn't get any proper response from support team as well.

**Comment by rishabhmaniyar** [comment]
Hey @niranjan92 we are already worked over a much better and an an interactive Scrip Master which will be updated automatically.
Probably will update it soon.

**Comment by qalpesh** [comment]
try this link
https://images.5paisa.com/website/scripmaster-csv-format.csv

Note: There is another way to get the scrip code from 5paisa API

**Comment by raj-adroit** [comment]
Here is the updated solution to get scrip_code for options
```py
from py5paisa import FivePaisaClient

client = FivePaisaClient(email="random_email@xyz.com", passwd="password", dob="YYYYMMDD")
client.login()

req_list_=[{"Exch":"N","ExchType":"D","Symbol":"NIFTY 22 APR 2021 CE 15200.00","Expiry":"20210422","StrikePrice":"15200","OptionType":"CE"}]
            
feed = client.fetch_market_feed(req_list_)

token = feed['Data'][0]['Token']

## token is the scrip_code for the option
```

**Comment by tanaynub** [comment]
isnt there a function to pull all stocks' and contracts' scrip wise details? including token??

**Comment by 2003vivek** [comment]
i am using the 5paisa api but i don't know how can i get the historical data for 1m timeframe using script code of banknifty. Please help me with the latest documentation?
