### ISSUE TITLE
Unable to cancel orders.

### ISSUE THREAD

**Issue by smit-s** [5paisa/py5paisa#37]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

Unable to cancel orders. 

### What I Did
Following is my request

```
mod_order=Order(order_type=OrderType.BUY, scrip_code=scrip_code,quantity=qty,
              order_for=OrderFor.CANCEL, exchange=Exchange.NSE, exchange_segment=ExchangeSegment.CASH, exch_order_id=order_id,
              atmarket=False, is_intraday=False,price=price)
        resp=self.client.place_order(mod_order)
```

I always get  **00:57:48 | Order information not found**   error.

I called it via a function using which I was trying to cancel an order. The json object obtained using order_book() for order that I was trying to cancel is as follows:

{'AHProcess': 'N', 'AfterHours': 'Y', 'AtMarket': 'N', 'BrokerOrderId': 383048970, 'BrokerOrderTime': '/Date(1611512627467+0530)/', 'BuySell': 'B', 'DelvIntra': 'D', 'DisClosedQty': 0, 'Exch': 'B', 'ExchOrderID': '383048970', 'ExchOrderTime': '/Date(315513000000+0530)/', 'ExchType': 'C', 'MarketLot': 1, 'OldorderQty': 0, 'OrderRequesterCode': '56105291       ', 'OrderStatus': 'AH Placed           ', 'OrderValidUpto': '24 Jan 2021', 'OrderValidity': 0, 'PendingQty': 1, 'Qty': 1, 'Rate': 73.3, 'Reason': '', 'RequestType': 'P', 'SLTriggerRate': 0, 'SLTriggered': 'N', 'SMOProfitRate': 0, 'SMOSLLimitRate': 0, 'SMOSLTriggerRate': 0, 'SMOTrailingSL': 0, 'ScripCode': 500469, 'ScripName': 'FEDERALBNK', 'TerminalId': 0, 'TradedQty': 0, 'WithSL': 'N'}

Can someone please tell me how shall I form a request in order to cancel this order via api?

**Comment by smit-s** [comment]
Edit: I figured out way to cancel order via postman. however when I use same body parameters in python request it gives following error
 02:25:35 | 0:Client handler to Exchange Connector connection stopped

while debugging I came to know that 3 more parameters user id, password and my2PIN gets added to body. 

Can someone help me find where is the issue?

**Comment by rishabhmaniyar** [comment]
Hey @smit-s  yes you are right email ,password and dob(my2PIN) get added to body in the request posted.
Please retry if it works after encrypting using the encryptor on developer docs page.
This is solved in python SDK, so for cancelling an order you will have to send your placed order's returned Exchange Order Id to modify or cancel any order.

Regards.

**Comment by smit-s** [comment]
Thanks for the help.
