### ISSUE TITLE
How to put in AMO orders?

### ISSUE THREAD

**Issue by SudoCode7** [5paisa/py5paisa#43]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by coder-amogh** [comment]
Check "Placing offline orders" section: https://5paisa.github.io/usage/place/

**Comment by SudoCode7** [comment]
> Check "Placing offline orders" section: https://5paisa.github.io/usage/place/
> 
> AND DON'T FORGET TO INSERT `atmarket = False` IN THE ORDER, OTHERWISE THE ORDER WOULD GET EXECUTED AT MARKET RATE!

Hey Thx,
But it is firing me this error after putting amo order.

ERROR - '21:56:28 | Exchange is closed. Market Order cannot be placed in After Hours, please provide Limit Rate'

whereas my code is in accord with the doc....
order = Order(order_type=OrderType.SELL, scrip_code=532174, quantity=1,
                           ahplaced=AHPlaced.AFTER_MARKET_CLOSED,price=578.34)

**Comment by coder-amogh** [comment]
Exactly what I told you, add atmarket=False and I think it should work.

**Comment by SudoCode7** [comment]
> atmarket=False

THx, 
Superb it worked!!!!!!!!
