### ISSUE TITLE
Unable to place FnO orders 

### ISSUE THREAD

**Issue by niranjan92** [5paisa/py5paisa#46]
* 5paisa Python SDK version: 0.1.8
* Python version: 3.8.5
* Operating System: Ubuntu

### Description

Unable to place FnO orders due to `Scrip does not exist` error. Cash orders working fine.

using scrip_code = `59706` for `NIFTY2140115000CE` . The same scrip code is seen in UI when I inspect using Chrome Debugger. 

### What I Did

I am trying to place order for buying `NIFTY2140115000CE` 1 lot using 
``` 
test_order = Order(order_type=OrderType.BUY, scrip_code='59706', exchange_segment=ExchangeSegment.DERIVATIVE, quantity=75)
client.place_order(test_order)
```

However, I get following response 

```
 20:38:20 | Scrip does not exist
{'BrokerOrderID': 0,
 'ClientCode': 'xxxxx',
 'Exch': 'B',
 'ExchOrderID': '',
 'ExchType': 'D',
 'LocalOrderID': 0,
 'Message': 'Scrip does not exist',
 'RMSResponseCode': 1,
 'ScripCode': 59706,
 'Status': 0,
 'Time': '/Date(1617203300886+0530)/'}
```

Am I missing anything here? 

Thanks in advance,

**Comment by rishabhmaniyar** [comment]
@niranjan92 
Seems like you missed to add price in there.
Retry and let me know your scrip code seems fine here.

Regards

**Comment by niranjan92** [comment]
Thanks for the quick response. issue resolved.
