### ISSUE TITLE
ExchangeType module dosen't exists in the pacakage!!

### ISSUE THREAD

**Issue by SudoCode7** [5paisa/py5paisa#47]
ANY GET AROUND TO THIS??

code:
from py5paisa import FivePaisaClient
from py5paisa.order import OrderForStatus, Exchange, RequestList, ExchangeType

client = FivePaisaClient(xxxxxxxx)
client.login()
test_order_status = OrderForStatus(exchange=Exchange.NSE, scrip_code=11915, order_id=0, exchange_type=ExchangeType.CASH)

Error:
Traceback (most recent call last):
  File "C:\Users\Phantom\PycharmProjects\Quanta\test3.py", line 2, in <module>
    from py5paisa.order import OrderForStatus, Exchange, RequestList, ExchangeType
ImportError: cannot import name 'ExchangeType' from 'py5paisa.order' (C:\Users\Phantom\AppData\Local\Programs\Python\Python39\lib\site-packages\py5paisa\order.py)

**Comment by coder-amogh** [comment]
Check this: #31

**Comment by SudoCode7** [comment]
If exchangetype module won't exist in the package then many functions like  fetch_trade_info(req_list) or fetch_order_status(req_list) won't work at all for me.... can you pls do it asap, cus it's has been a pending issue for  a long time!!!

**Comment by coder-amogh** [comment]
> If exchangetype module won't exist in the package then many functions like fetch_trade_info(req_list) or fetch_order_status(req_list) won't work at all for me.... can you pls do it asap, cus it's has been a pending issue for a long time!!!

You have to use ExchangeSegment and all should work well...

**Comment by SudoCode7** [comment]
> > If exchangetype module won't exist in the package then many functions like fetch_trade_info(req_list) or fetch_order_status(req_list) won't work at all for me.... can you pls do it asap, cus it's has been a pending issue for a long time!!!
> 
> You have to use ExchangeSegment and all should work well...

Hi Amogh,
Can you please direct me to ExchangeSegment module as I am unable to find it inside the documentation....?

**Comment by coder-amogh** [comment]
> Hi Amogh,
> Can you please direct me to ExchangeSegment module as I am unable to find it inside the documentation....?

Check this: https://github.com/5paisa/py5paisa/blob/master/py5paisa/order.py#L17

**Comment by SudoCode7** [comment]
> > Hi Amogh,
> > Can you please direct me to ExchangeSegment module as I am unable to find it inside the documentation....?
> 
> Check this: https://github.com/5paisa/py5paisa/blob/master/py5paisa/order.py#L17

Thanks Amogh
