### ISSUE TITLE
How to place VTD Order? 

### ISSUE THREAD

**Issue by SudoCode7** [5paisa/py5paisa#48]
I am desperately trying to place VDT order as specified in the last of this doc- 'https://forum.5paisa.com/portal/en/kb/articles/types-of-stock-trading-order-and-its-validity'

And once I place this, would it be the same to modify it as specified in the doc?

**Comment by SudoCode7** [comment]
order_validity=OrderValidity.GTD  using this isn't helping in Order()!!!

Any better soln by you all guys?

**Comment by coder-amogh** [comment]
> order_validity=OrderValidity.GTD using this isn't helping in Order()!!!
> 
> Any better soln by you all guys?

Can you paste complete code?

**Comment by SudoCode7** [comment]
> > order_validity=OrderValidity.GTD using this isn't helping in Order()!!!
> > Any better soln by you all guys?
> 
> Can you paste complete code?

order = Order(order_type=OrderType.SELL, scrip_code=script_code, quantity=quantity,
                          price=close_price,stoploss_price=stoploss,is_intraday=False, atmarket=False, order_validity=OrderValidity.GTD)
client.place_order(order)

**Comment by coder-amogh** [comment]
> > > order_validity=OrderValidity.GTD using this isn't helping in Order()!!!
> > > Any better soln by you all guys?
> > 
> > 
> > Can you paste complete code?
> 
> [code]

You need to pass is_vtd = True

**Comment by SudoCode7** [comment]
> > > > order_validity=OrderValidity.GTD using this isn't helping in Order()!!!
> > > > Any better soln by you all guys?
> > > 
> > > 
> > > Can you paste complete code?
> > 
> > 
> > [code]
> 
> You need to pass is_vtd = True

Then what will be the argument for giving in the order expiry date?

**Comment by SudoCode7** [comment]
> > > > > order_validity=OrderValidity.GTD using this isn't helping in Order()!!!
> > > > > Any better soln by you all guys?
> > > > 
> > > > 
> > > > Can you paste complete code?
> > > 
> > > 
> > > [code]
> > 
> > 
> > You need to pass is_vtd = True
> 
> Then what will be the argument for giving in the order expiry date?

will it by default consider it as 45 days?

**Comment by coder-amogh** [comment]
> > > > > > order_validity=OrderValidity.GTD using this isn't helping in Order()!!!
> > > > > > Any better soln by you all guys?
> > > > > 
> > > > > 
> > > > > Can you paste complete code?
> > > > 
> > > > 
> > > > [code]
> > > 
> > > 
> > > You need to pass is_vtd = True
> > 
> > 
> > Then what will be the argument for giving in the order expiry date?
> 
> will it by default consider it as 45 days?

From the code, it seems that it will be only valid till next day. Maybe you can try passing a custom datetime object in `vtd = {datetime_object}`
