### ISSUE TITLE
404 not found for pip install pyp5aisa

### ISSUE THREAD

**Issue by Prateekm11** [5paisa/py5paisa#49]
Command  "pip install pyp5aisa" responds with 404 not found. looks like api5paisa is the actual name.
Is this correct if yes please update the readme installation steps.

**Comment by anilgupta83** [comment]
try:
pip install py5paisa
(not pyp5aisa)
there's a typo in the install instructions

**Comment by Prateekm11** [comment]
yes pyp5paisa worked but the name will need corrcetion in readme

**Comment by invinciblycool** [comment]
Hey @Prateekm11 
Thanks for the report, I've corrected the installation in the README
