### ISSUE TITLE
BO order for options

### ISSUE THREAD

**Issue by mpunekar** [5paisa/py5paisa#51]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

Is it possible to place BO order for options? I tried to use correct script code which works with regular order but it doesn't work with bo_co_order and bo_order. The problem seems to be that I can't pass exchange and exchange_segment to bo_co_order. Can you please provide appropriate function calls?

**Comment by coder-amogh** [comment]
Can you paste the code?

**Comment by coder-amogh** [comment]
Do you have enough margin?
Is the Qty 75 or 50? NSE has changed the lot size from 75 to 50. Try with that?

**Comment by mpunekar** [comment]
> Do you have enough margin?
> Is the Qty 75 or 50? NSE has changed the lot size from 75 to 50. Try with that?

I appreciate that you want to help but I think you have no idea about this problem. So please don't waste your and my time!

**Comment by coder-amogh** [comment]
> I am a regular trader and trade up to 10 lots a day whereas I don't think you even trade options. I appreciate that you want to help but I think you have no idea about this problem. So please don't waste your and my time!

Ok
