### ISSUE TITLE
Issue with requesting market feed for BANKNIFTY FUT 

### ISSUE THREAD

**Issue by jegan1994** [5paisa/py5paisa#54]
* 5paisa Python SDK version:
* Python version:
* Operating System:

Issue with market feed while requesting for BANKNIFTY FUT 

I Used the below code
req_list_=[{"Exch":"N","ExchType":"D","Symbol":"BANKNIFTY 27 MAY 2021 FUT","Expiry":"20210527","StrikePrice":"0","OptionType":""}]

**Comment by jegan1994** [comment]
I Used the below code also. But couldn't fetch
req_list_=[{"Exch":"N","ExchType":"D","Symbol":"BANKNIFTY 27 MAY 2021","Expiry":"20210527","StrikePrice":"0","OptionType":""}]

**Comment by rishabhmaniyar** [comment]
Hey @jegan1994 

Please put OptionType:"XX"

**Comment by jegan1994** [comment]
It Works!
