### ISSUE TITLE
Sandbox availability for testing 

### ISSUE THREAD

**Issue by shivkumr-code** [5paisa/py5paisa#55]
how to test the code that I write using the rest apis?? Is there any paper trading/sandbox kind of thing available to make sure the parameters are correctly passed and the order is placed. I just down want to play with real money and real trades just for testing.

**Comment by coder-amogh** [comment]
Just create your own testing sandbox script for it, and in testing mode hit your own URL and do what you need to do. For example, you can throw in the order parameters and the testing sandbox script would just log that in the database or write it to a file, email you, or just simply print it. 

Or you can just use `AMO` or `atMarket=False`while placing orders, and then check what was expected and what has happened through the website/app.
