### ISSUE TITLE
Cover Order

### ISSUE THREAD

**Issue by ysravankumar** [5paisa/py5paisa#6]
I dont find any flag to indicate the order is cover order or bracket order.
`    test_order = Order(order_type=OrderType.BUY, scrip_code=3045, quantity=1, exchange=Exchange.NSE, is_intraday=True, stoploss_price=185)
`
can you please check and update example

**Comment by invinciblycool** [comment]
Thanks for your interest in `py5paisa`!
Placing cover and bracket orders has already been lined up, and will soon be added to the SDK.

**Comment by coder-amogh** [comment]
> Placing cover and bracket orders has already been lined up, and will soon be added to the SDK.

Hi, any update on this? It's been too long. This feature is already there on the web platform, I don't know why it's taking so much time to add it to the API although this is been most required feature of all time... :(

**Comment by coder-amogh** [comment]
This issue can be closed now.
