### ISSUE TITLE
Unable To Login, KeyError: 'JwtToken'

### ISSUE THREAD

**Issue by Arsh0023** [5paisa/py5paisa#61]
* 5paisa Python SDK version: 0.2.5
* Python version: 3.8.5
* Operating System: Windows 10

### Description
I am unable to login and KeyError is raised.
I've replaced my initials with *****.

### What I Did

```
from py5paisa import FivePaisaClient

client = FivePaisaClient(email="****************", 
                        passwd="********", 
                        dob="************")
client.login()

```
### Output:-

```
KeyError                                  Traceback (most recent call last)
<ipython-input-2-8d108aabc229> in <module>
      4                         passwd="*********",
      5                         dob="***********")
----> 6 client.login()

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\py5paisa\py5paisa.py in login(self)
     62         self.login_payload["body"]["My2PIN"] = secret_dob
     63         self.login_payload["head"]["requestCode"] = "5PLoginV3"
---> 64         res = self._login_request(self.LOGIN_ROUTE)
     65         message = res["body"]["Message"]
     66         if message == "":

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\py5paisa\py5paisa.py in _login_request(self, route)
     86         session_cookies = res.cookies
     87         cookies_dictionary = session_cookies.get_dict()
---> 88         self.Jwt_token=cookies_dictionary['JwtToken']
     89 
     90         return res.json()

KeyError: 'JwtToken'
```
Can Anyone please help me out with this.Thanks.
Best,
Arshpreet Singh

**Comment by Arsh0023** [comment]
@5paisa Can you please look into this issue.

**Comment by pawarvijay** [comment]
@Arsh0023 take a look at this 5 paisa video of configuration, 
if u have missed anything config stuff
https://www.youtube.com/watch?v=xW0Qmd5t3PU

**Comment by Arsh0023** [comment]
@pawarvijay I've followed this video earlier and I am pretty sure that I haven't misconfigured anything.And I've also tried first using the my actual email and dob and then also using the encrypted one i got from Authorization tab in 5paisa API. But it didn't worked for me :(

**Comment by Arsh0023** [comment]
I placed my first order on 5paisa and after that for some reason I am able to login using API. But still when I try to login using the encrypted credentials then it shows the same error again.

**Comment by PratikMahobiya** [comment]
I'm also getting same error, Please Help...

**Comment by pv-ajay-thota** [comment]
I tried resetting my password. and logged in again.. somehow it worked.

**Comment by saurav2210** [comment]
Create new project and try to configure again..

**Comment by 5paisa** [comment]
Hey @Arsh0023 and everyone facing the same issue,

Kindly keep your credentials strictly as per instructions given in documentation.
Please make sure credentials are not in " " (double quotes) and not to skip on [KEYS] in the first line.
Also the keys.conf file should be in the same folder as your project.
