### ISSUE TITLE
Chgange In OI

### ISSUE THREAD

**Issue by saurav2210** [5paisa/py5paisa#63]
Anyone know how to get Change in OI data ?

**Comment by 5paisa** [comment]
Hi @saurav2210 ,

You can get it with market snapshot api .

**Comment by saurav2210** [comment]
Thanks for reply,

I am using Python SDK.

In Market feed api did't get OI
Market feed response : 
==> {"CacheTime": 5, "Data": [{"Exch": "N", "ExchType": "D", "High": 73.75, "LastRate": 63.3, "Low": 43, "PClose": 41.2, "TickDt": "/Date(1622620788000+0530)/", "Time": 26988, "Token": 41240, "TotalQty": 74374950}], "Message": "Success", "Status": 0, "TimeStamp": "/Date(1622620788000+0530)/"}
 

Live Market Streaming for Open interest :
response :
==>{"Exch":"M","ExchType":"D","Token":228530,"OpenInterest":17531,"DayHiOI":4798600,"DayLoOI":4777600}

In both api did not get Change in OI.
Can you Please add change in Oi in Live Market Streaming (Open interest) 
Currently in response we got OI,DayHiOI,DayLoHi

**Comment by qalpesh** [comment]
try 
req_list=[
            { "Exch":"N","ExchType":"C","ScripCode":1660},
            
            ]

dict1=Client.Request_Feed('oi','s',req_list)

client.Streming_data(dict1)

Note: Use the following abbreviations :

Market Feed=mf

Market Depth (upto 5)=md

Open Interest=oi

Subscribe= s

Unsubscribe=u

**Comment by saurav2210** [comment]
Thanks for that but as this code give OI(OI,Day Highest OI ,Day Low OI) in response instead of Change In OI. I am looking for Change in OI

**Comment by 5paisa** [comment]
Hi @saurav2210 ,

We might get that feature added soon.
Till then please log it and use the difference for Change In OI data.
