### ISSUE TITLE
How to find scrip code for Options

### ISSUE THREAD

**Issue by gauravsuman8** [5paisa/py5paisa#66]
* 5paisa Python SDK version: 0.2.7
* Python version: 3.9.1
* Operating System: MacOS

### Description
I am unable to find the scrip code for order placement for banknifty options. 
As per readme the URL mentioned is https://www.5paisa.com/docs/default-source/scrip-master/scripmaster-csv-format.csv
but this seems to be a broken url. Please update the readme with latest URL for scrip master.

**Comment by pushand** [comment]
same here. the developers could easily update such a major fix, if really concerned. No script no API trading whats the point

**Comment by pushand** [comment]
@gauravsuman8 in case if you still haven't figured out or for someone else looking, you can use market feed API to get scrip code. It comes ins response key as Token

`https://Openapi.5paisa.com/VendorsAPI/Service1.svc/MarketFeed`

**Comment by pushand** [comment]
how to get bank nifty @gauravsuman8 any idea? is symbol passed corret. I'm getting response for stocks but not for options

`{"Exch":"N","ExchType":"D","Symbol":"BANKNIFTY21JUN35200CE","Expiry":"20210624","StrikePrice":"35200","OptionType":"CE"}`

**Comment by gauravsuman8** [comment]
@pushand No the symbol should be passed as "BANKNIFTY 10 JUN 2021 CE 35400.00"

**Comment by gauravsuman8** [comment]
@pushand any idea about https://github.com/5paisa/py5paisa/issues/67 ?

**Comment by 5paisa** [comment]
> * 5paisa Python SDK version: 0.2.7
> * Python version: 3.9.1
> * Operating System: MacOS
> 
> ### Description
> I am unable to find the scrip code for order placement for banknifty options.
> As per readme the URL mentioned is https://www.5paisa.com/docs/default-source/scrip-master/scripmaster-csv-format.csv
> but this seems to be a broken url. Please update the readme with latest URL for scrip master.

Hey guys,
The above link is not working anymore.
Please use - https://images.5paisa.com/website/scripmaster-csv-format.csv

**Comment by mr-easy** [comment]
@5paisa Can you tell the scrip master file's column meaning? Like what is WireCat, Series, etc.
