### ISSUE TITLE
Order status API returning empty object. 

### ISSUE THREAD

**Issue by gauravsuman8** [5paisa/py5paisa#67]
* 5paisa Python SDK version: 0.2.7
* Python version: 3.9.1
* Operating System: MacOS

### Description

I am trying to query the Order status and Trade Information API but it is returning an empty object instead of order status and trade information.

Sample code:
```
def get_order_average():

    req_list = [
        {
            "Exch": "N",
            "ExchType": "D",
            "ScripCode": 35304,
            "ExchOrderID": "1400000010626123"
        }]
    r = client.fetch_order_status(req_list)
    print(r)
```

Response:

```
18:15:06 | Logged in!!
 18:15:07 | Success
18:15:07 | 
{'Message': '', 'OrdStatusResLst': [], 'Status': 0}
```

Please help me with this.
@5paisa

**Comment by gauravsuman8** [comment]
can anyone help me with this?
@5paisa

**Comment by pushand** [comment]
API Document says they want 
`"RemoteOrderID": "90980441"`

I tried with all broker, exchange and remote none of them worked it was empty. Doc say we should set remote order Id I tried setting both numeric and alphanumeric while placing order but still didn;t worked

**Comment by pushand** [comment]
I think you need to first get trades and in that, you will get Remote order id which then(remote order ID) can be used to query order status

**Comment by gauravsuman8** [comment]
@pushand i was trying to fetch trade_information also using 
req_list = [
        {
            "Exch": "N",
            "ExchType": "D",
            "ScripCode": 35304,
            "ExchOrderID": "1400000010626123"
        }]
    r = client.fetch_trade_info(req_list)
    print(r)
In this i think ExchOrderID is required but it is also returning me empty object.

**Comment by gauravsuman8** [comment]
and also is there an API for fetching trade book. I saw api for order book but didn't find anything to get all trades.

**Comment by pushand** [comment]
No API as per their document to get the trades List and also nothing seems working, getting empty response
@5paisa 

```
trade payload {"head":{"appName":"xx","appVer":"1.0","appSource":"xx","key":"xx","osName":"WEB","requestCode":"5PTrdInfo","userId":"xx","password":"xx"},"body":{"ClientCode":"xx","TradeInformationList":[{"Exch":"N","ExchType":"D","ScripCode":43938,"RemoteOrderID":"6","BrokerOrderID":472976780,"ExchOrderID":"1400000056434987"}]}}
trade response {"body":{"Message":"","Status":0,"TradeDetail":[]},"head":{"responseCode":"5PTrdInfo","status":"0","statusDescription":"Success"}}
```

**Comment by gauravsuman8** [comment]
Anyone from @5paisa can you please look into the issue as multiple people are facing the same issue.

**Comment by gauravsuman8** [comment]
@pushand is the trade api working for you?

**Comment by gauravsuman8** [comment]
very bad support from @5paisa team for developers.

**Comment by pushand** [comment]
> @pushand is the trade book api working for you?
> It's showing me {
> "Message": "Error while processing"
> }

facing the same error. @5paisa please care to at least reply @ba11b0y can you help?

**Comment by pushand** [comment]
@gauravsuman8 I was able to get order status. when you place an order create a remote order id preferably int type and then to get order status pass that remote id

Request
`
{
  "head": {
    "appName": "xx",
    "appVer": "1.0",
    "appSource": "xx",
    "key": "xx",
    "osName": "WEB",
    "requestCode": "5POrdStatus",
    "userId": "xx",
    "password": "xx"
  },
  "body": {
    "ClientCode": "xx",
    "OrdStatusReqList": [
      {
        "Exch": "N",
        "ExchType": "D",
        "ScripCode": 51061,
        "RemoteOrderID": "37242839564926615038"
      }
    ]
  }
}
`

Response
`
{
  "body": {
    "Message": "",
    "OrdStatusResLst": [
      {
        "Exch": "N",
        "ExchOrderID": 1600000010127445,
        "ExchOrderTime": "\/Date(1623816735000+0530)\/",
        "ExchType": "D",
        "OrderQty": 50,
        "OrderRate": 91.45,
        "PendingQty": 0,
        "ScripCode": 51061,
        "Status": "Placed",
        "Symbol": "BANKNIFTY 17 Jun 2021 PE 35000.00",
        "TradedQty": 50
      }
    ],
    "Status": 0
  },
  "head": {
    "responseCode": "5POrdStatus",
    "status": "0",
    "statusDescription": "Success"
  }
}
`

**Comment by gauravsuman8** [comment]
@pushand thanks for this. Are you able to fetch trade information now?

**Comment by pushand** [comment]
> @pushand thanks for this. Are you able to fetch trade information now?

nope gets status code 3

Request
` {"head":{"appName":"xx","appVer":"1.0","appSource":"xx","key":"xx","osName":"WEB","requestCode":"5PTrdInfo","userId":"xx","password":"xx"},"body":{"ClientCode":"xx","TradeInformationList":[{"Exch":"N","ExchType":"D","ScripCode":51061,"RemoteOrderID":"39676166526184522125"},{"Exch":"N","ExchType":"D","ScripCode":43934,"RemoteOrderID":"14462175147018949377"}]}}`

Respons
`{"body":{"Message":"Invalid input parameters.","Status":3,"TradeDetail":[]},"head":{"responseCode":"5PTrdInfo","status":"0","statusDescription":"Success"}}`

**Comment by gauravsuman8** [comment]
yeah same issue for me and if you pass exchange order id in place of remote order id, it will return empty object.

**Comment by pushand** [comment]
Mr India @5paisa wo hara wala button daba k  thoda samne aavo

**Comment by 5paisa** [comment]
> @pushand is the trade book api working for you?
> It's showing me {
> "Message": "Error while processing"
> }

Hey @pushand ,
Please share our request. Will with the solution

**Comment by 5paisa** [comment]
We have not deprecated any API's which are listed on our page.
Kindly note :- Order Status API (takes RemoteOrderID) and Trade Information API (takes ExchOrderID)

**Comment by gauravsuman8** [comment]
Hi @5paisa 

> @pushand i was trying to fetch trade_information also using
> req_list = [
> {
> "Exch": "N",
> "ExchType": "D",
> "ScripCode": 35304,
> "ExchOrderID": "1400000010626123"
> }]
> r = client.fetch_trade_info(req_list)
> print(r)
> In this i think ExchOrderID is required but it is also returning me empty object.
> Am I missing something in this?

this is the body i have put to fetch trade information. As mentioned by u the trade information API takes ExchOrderID, i have used the same in the body. Can you please tell why am i getting empty response.

**Comment by 5paisa** [comment]
> Hi @5paisa
> 
> > @pushand i was trying to fetch trade_information also using
> > req_list = [
> > {
> > "Exch": "N",
> > "ExchType": "D",
> > "ScripCode": 35304,
> > "ExchOrderID": "1400000010626123"
> > }]
> > r = client.fetch_trade_info(req_list)
> > print(r)
> > In this i think ExchOrderID is required but it is also returning me empty object.
> > Am I missing something in this?
> 
> this is the body i have put to fetch trade information. As mentioned by u the trade information API takes ExchOrderID, i have used the same in the body. Can you please tell why am i getting empty response.

Hi,
I am looking into!
Please give some time to resolve.

**Comment by 5paisa** [comment]
Hi all,

Please try using Trade Information API now let me know if still facing any issues.

**Comment by gauravsuman8** [comment]
> Hi all,
> 
> Please try using Trade Information API now let me know if still facing any issues.

Hi @5paisa 
I am still facing the same issue while fetching trade information. 
Body - 
    def get_trade_information(self):
        req_list = [
            {
                "Exch": "N",
                "ExchType": "D",
                "ScripCode": 50051,
                "ExchOrderID": "1400000103609021"
            }]

        r = self.client.fetch_trade_info(req_list)
        print(r)
Response -
 15:48:11 | Logged in!!
 15:48:11 | 
{'Message': '', 'Status': 0, 'TradeDetail': []}
None

**Comment by qalpesh** [comment]
Other way around is to get order history using below line
order_list = client.order_book()
and then query particular trade using 'ExchOrderID'
this works for me
