### ISSUE TITLE
historical data for day

### ISSUE THREAD

**Issue by Rahulghuge94** [5paisa/py5paisa#68]
is there any way to get historical data?

**Comment by pushand** [comment]
no use Zerodha kite connect for that you need to shell out 2k/mth for that

**Comment by rishabhmaniyar** [comment]
Hi @Rahulghuge94  and @pushand ,
You can not get historical data even in 5Paisa- https://github.com/5paisa/py5paisa#historical-data

**Comment by 5paisa** [comment]
> Hi @Rahulghuge94 and @pushand ,
> You can not get historical data even in 5Paisa- https://github.com/5paisa/py5paisa#historical-data

It is absolutely free of cost historical data with 5Paisa!
