### ISSUE TITLE
CRITICAL - Renew API key

### ISSUE THREAD

**Issue by pushand** [5paisa/py5paisa#71]
**### CRITICAL** 
There's no way to regenerate a new API key if it's stolen/compromised. 
Kindly allow user to generate a new API key from this below page
https://invest.5paisa.com/DeveloperAPI/APIKeys

**Comment by 5paisa** [comment]
Hi @pushand ,

Currently we don't have that provision at user end.
But surely, if you have compromised your credentials, please highlight it to us in support@5paisa.com mail.
