### ISSUE TITLE
How to get Open price with API

### ISSUE THREAD

**Issue by jegan1994** [5paisa/py5paisa#72]
My strategy needs opening price of the script. How to get the exact open price of the script with 5 paisa API?. I see I can get LTP, High and Low but not Open price.

**Comment by jegan1994** [comment]
Solved the issue by using websocket

**Comment by yashwin2018** [comment]
def spot_ltp():

    req_list1=[
            { "Exch":"N","ExchType":"C","ScripCode":999920005},
            ]
    dict1=client.Request_Feed('mf','s',req_list1)
    def on_message(ws, message):
        x=json.loads(message.replace("[","").replace("]",""))["LastRate"]
        print(x)
        client.close_data()
    client.receive_data(on_message)
