### ISSUE TITLE
unable to modify triggersl price

### ISSUE THREAD

**Issue by Rahulghuge94** [5paisa/py5paisa#74]
in bo order it is not all allowing to modify sl. it says 
o=Order(order_type='S', scrip_code=3456, quantity=1, price=0,is_intraday=True,exchange='N',exchange_segment='C',atmarket=True,exch_order_id="1300000014546550" ,stoploss_price=342,is_stoploss_order=True,order_for='M')
>>> client.mod_bo_order(o)
[32m 13:58:59[0m | [1mOrder rejected by RMS. Price difference should be 1.75 between stop loss and profit order price[0m
{'AddReqMgn': 0, 'AvlbMgn': 0, 'BrokerOrderID': 478051947, 'ClientCode': '50317535', 'Exch': 'N', 'ExchOrderID': 1300000014546550, 'ExchType': 'C', 'LocalOrderID': 0, 'Message': 'Order rejected by RMS. Price difference should be 1.75 between stop loss and profit order price', 'RMSResponseCode': -152, 'ScripCode': 3456, 'Status': 1, 'Time': '/Date(1624300200000+0530)/'}

on 5paisa web terminal we can do the same. but here it trowing error.
can you please help. iso im not able to put normal stop loss order.

**Comment by 5paisa** [comment]
Hi @Rahulghuge94 ,

You can modify only legs of SL and target orders after execution of initial order.
Also, only allowing to change SL trigger price and not SL limit price in the same.

**Comment by Rahulghuge94** [comment]
not understand what you are trying to say.. this is acco. to your api documentation. you have on github. i did the same. if i can see any  video that will be very easy.

**Comment by 5paisa** [comment]
> not understand what you are trying to say.. this is acco. to your api documentation. you have on github. i did the same. if i can see any video that will be very easy.

Hi @Rahulghuge94 ,
We will share video for your reference later.
Please use modify api only to modify legs of your placed initial order.
