### ISSUE TITLE
Getting WSS feed to MySQL

### ISSUE THREAD

**Issue by jegan1994** [5paisa/py5paisa#76]
Hi all,

Greetings!

I am not sure how to catch the data that is coming from the WSS My code below 

from py5paisa import FivePaisaClient
from py5paisa.order import Order, OrderType, Exchange

Client = FivePaisaClient(email="xxxxxx@gmail.com", passwd="xxxxxxx", dob="19000101")
Client.login()

req_list=[
            { "Exch":"N","ExchType":"C","ScripCode":7}
            ]

dict1=Client.Request_Feed('mf','s',req_list)
Data = Client.Streming_data(dict1)

print(Data)

dict2=Client.Request_Feed('mf','u',req_list)
Client.Streming_data(dict2)

Output I get:

 00:11:09 | Logged in!!
Streaming Started
[{"Exch":"N","ExchType":"C","Token":7,"LastRate":877.1,"LastQty":100,"TotalQty":1848253,"High":910,"Low":873.05,"OpenRate":910,"PClose":438.55,"AvgRate":885.5,"Time":35830,"BidQty":0,"BidRate":0,"OffQty":0,"OffRate":0,"TBidQ":699,"TOffQ":0,"TickDt":"\/Date(-62135596800000)\/"}]

and the program is going to infinite loop. 

My Doubts:
**1. How to get the above JSON array to a Local variable in Python.
2. How to stop (unsubscribe) once I no longer require WS.
3. How to I get the [?][0]['LastRate'] value if I am using multiple script code (what should come in place of '?')**

I am new to WSS and python so please excuse me if doubts are silly.

Thanks in advance.

**Comment by gaucow** [comment]
Hey @jegan1994 - did you get the answer to these? I'm stuck at the same place and would really appreciate any help here! Thanks in advance :)
