### ISSUE TITLE
ScripMaster CSV does not have BANKNIFTY current week tokens

### ISSUE THREAD

**Issue by lokifr3k** [5paisa/py5paisa#79]
Hi 
i am looking for the tokens in scripmaster csv download, but it does not have current week weekly expiry tokens,
ex..  15 JULY Expiry 
pls advice what to do

**Comment by saikrisshnaa** [comment]
Hi, facing the same issue.
5paisa team, please suggest a way to get all the scrip_codes. scripmaster.csv contains only few scrips. Many scrips are missing in that,

**Comment by Rahulghuge94** [comment]
this guys are useless they will not listen. 5paisa is not trustworthy for api.

**Comment by rishabhmaniyar** [comment]
Hi guys,

This was solved now get the updated scrip master - https://images.5paisa.com/website/scripmaster-csv-format.csv
