### ISSUE TITLE
F&O Support

### ISSUE THREAD

**Issue by kiruthemes** [5paisa/py5paisa#8]
Hi,

Does the API support placing orders in Futures?

Regards,
Kiran

**Comment by invinciblycool** [comment]
Yes Kiran.
Just make sure that you get the correct scrip code and set the `ExchangeSegment` as `DERIVATIVE`

**Comment by invinciblycool** [comment]
Hey @kiruthemes , were you able to place orders.
If yes, please close this issue.

**Comment by srikanthbojja** [comment]
does this also work with Options

**Comment by coder-amogh** [comment]
> does this also work with Options

It should work with Options too, since Option is a derivative. You just need to pass the correct scrip code and it should work. Of course, how to find the scrip code still remains a big question ;)

**Comment by niranjan92** [comment]
@coder-amogh @invinciblycool has there been any update on this issue? How do I fetch latest scrip codes for options? 

I tried putting exchange token and instrument_token from zerodha's API, and that also didn't work. I am setting ExchangeSegment as derivative

**Comment by rishabhmaniyar** [comment]
@niranjan92 
Instrument tokens are different for different platforms.
We have market feed api at the moment which returns token.
But seeing the demand we are working over a separate dedicated api to fetch scrip code.

Regards.

**Comment by rishabhmaniyar** [comment]
> > does this also work with Options
> 
> It should work with Options too, since Option is a derivative. You just need to pass the correct scrip code and it should work. Of course, how to find the scrip code still remains a big question ;)

We have market feed api at the moment which returns token.
But seeing the demand we are working over a separate dedicated api to fetch scrip code.

**Comment by bhushanjawle** [comment]
Hi @rishabhmaniyar I see getting scrip_code has been open for about a year now. This comment from end of last quarter mentions there is way to get those using market feed API. I faced issue similar to #5 and #66 in getting scrip code .
Is there a working code to you can point to for this  ?
