### ISSUE TITLE
receiving false historical data for banknifty current month instrument.

### ISSUE THREAD

**Issue by Rahulghuge94** [5paisa/py5paisa#82]
im receiving false data while running algo. im not able to believe that this data is not matching with your chart.
this is not good you should stop the stream if there is any problem.
client.historical_data("N",'D',53179,str(5)+"m","2021-07-19","2021-07-19")

![Capture](https://user-images.githubusercontent.com/16452687/126117057-ce269de6-7d1e-4087-859d-3499af9cc449.PNG)
![image](https://user-images.githubusercontent.com/16452687/126117113-42d0ffcc-02b0-4eb3-97f4-842177cc4506.png)
not matching any candle..
 this is wrong.

**Comment by rishabhmaniyar** [comment]
This issue was temporary due to some glitch.
Please check again and let me know if occurs again!
