### ISSUE TITLE
No ExchOrderID assigned for placed order

### ISSUE THREAD

**Issue by qalpesh** [5paisa/py5paisa#83]
* 5paisa Python SDK version: 0.2.7
* Python version: 3.6
* Operating System: Windows 7

I executed below code for buy order. In response I got only BrokerOrderID and no ExchOrderID. From order book I tried to get the ExchOrderID but it returned Nil when I check on mobile app the order was executed. I face this problem regularly, is there better way to place order and track status of that particular order?

from py5paisa.order import Order, OrderType, Exchange

test_order = Order(order_type='B',exchange='N',exchange_segment='D', scrip_code=46898, quantity=25, price=160,is_intraday=True,atmarket=False)
client.place_order(test_order)

Response:
{'BrokerOrderID': 496882838, 'ClientCode': '52808434', 'Exch': 'N', 'ExchOrderID': '', 'ExchType': 'D', 'LocalOrderID': 0, 'Message': 'Success', 'RMSResponseCode': 0, 'ScripCode': 46898, 'Status': 0, 'Time': '/Date(1626892200000+0530)/'}

**Comment by ajaysekhri** [comment]
Hey facing same issue. How did it resolved for you ?

**Comment by qalpesh** [comment]
While passing an order pass unique remote order id (random number) and then fetch order status using the same remote order id. see below code.

random_number = 12872356123
new_odr = Order(order_type=order,
                                exchange='N',
                                exchange_segment='D',
                                scrip_code=scr, quantity=qty, price=prc, is_intraday=intraday,
                                atmarket=atmkt, is_stoploss_order=slmkt, stoploss_price=slprc,
                                disqty=0, remote_order_id=random_number)

req_list_ = [

            {
                "Exch": "N",
                "ExchType": "D",
                "ScripCode": scr,
                "RemoteOrderID": random_number
            }]
        order = client.fetch_order_status(req_list_)
        order_id = order['OrdStatusResLst'][0]['ExchOrderID']
