### ISSUE TITLE
Issue while fetching multiple script via streaming data 

### ISSUE THREAD

**Issue by jegan1994** [5paisa/py5paisa#84]
Whenever I fetch 1 instrument market data via websocket it works well. But not able to fetch multiple script via websocket array. Please help.

**Comment by rishabhmaniyar** [comment]
Hi @jegan1994 ,

It will push data as and when their is data change. In case you subscribe for multiple scrips then you have to handle information  tagging it with the scrip code for easier and accurate use case.
