### ISSUE TITLE
Issue in processing the websockets streaming live data

### ISSUE THREAD

**Issue by Parthiban-Sampath** [5paisa/py5paisa#88]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

When I stream live data, it prints as text. I could not able to process it. I tried to modify py5paisa to process but could not succeed.
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by 5paisa** [comment]
Hi,
Try using json.loads() and convert the string response of websocket to python dictionary

**Comment by salilshukla9** [comment]
Can we have sample code for this.

**Comment by Parthiban-Sampath** [comment]
I have used json.loads() and it worked. 
Thank you
