### ISSUE TITLE
how to place limit order

### ISSUE THREAD

**Issue by jugs695369** [5paisa/py5paisa#9]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

i am not able to find how to place the **limit order**

**Comment by invinciblycool** [comment]
@jugs695369 To place a limit order, use the below according to your use case.

```py
from py5paisa import FivePaisaClient
from py5paisa.order import Order, OrderType, Exchange

client = FivePaisaClient(email="xyz@email.com",
                         passwd="password", dob="YYYYMMDD")
client.login()
order = Order(order_type=OrderType.BUY, scrip_code=11111, atmarket=False,
              exchange=Exchange.NSE, quantity=1, price=30.5)
client.place_order(order)

```
Passing `atmarket=False` does the trick, and also make sure the price is in the circuit limit.

**Comment by jugs695369** [comment]
Ok thanks i will try this

**Comment by invinciblycool** [comment]
Please close this issue if if you were able to place an order successfully.

Thanks
Rahul.
