### ISSUE TITLE
Issue in placing SL order

### ISSUE THREAD

**Issue by jrdinesh** [5paisa/py5paisa#95]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

When trying to place an SL order through python the order gets placed but it gets rejected from the exchange with this error message 
"Invalid combination Of mf/aon/disclosed volume"

### What I Did
Order(order_type='B', exchange='N', exchange_segment='D', scrip_code=40336, quantity=50,price=100, is_intraday=True, atmarket=False,is_stoploss_order=True, stoploss_price=99)

```

**Comment by Rahulghuge94** [comment]
sl order works when u have open position for that scrip. if u try to place direct sl order it would not get placed.

**Comment by balgates1** [comment]
Hi Rahu,

Thanks for your response, Please refer to the Screenshot below. I have open positions on Nifty 02 SEP 16500 PE. when I try to place SL regular order it's rejected by the exchange. 

Error Message : 'Reason': 'Invalid combination Of mf/aon/disclosed volume.',

![image](https://user-images.githubusercontent.com/89125650/131624318-4b8b09e2-9c5a-42a0-ba0b-7136793bd844.png)

**Comment by jrdinesh** [comment]
Yeah this needs to be resolved if v can't place SL order its highly risky

**Comment by jrdinesh** [comment]
@5paisa Can you guys have a look into this...

**Comment by qalpesh** [comment]
Add disqty=0 to the order and it should work. 
e.g.
Order(order_type='B', exchange='N', exchange_segment='D', scrip_code=40336, quantity=50,price=100, is_intraday=True, atmarket=False,is_stoploss_order=True, stoploss_price=99, disqty=0 )

**Comment by jrdinesh** [comment]
Oh okay i will verify this...

**Comment by jrdinesh** [comment]
Ok it did work but in response i am not getting Exchange Order ID -  Its Blank for some reason... any idea how to get exchange order id from this "BrokerOrderID"

**Comment by jrdinesh** [comment]
Ok it did work but in response i am not getting Exchange Order ID - Its Blank for some reason... any idea how to get exchange order id from this "BrokerOrderID"

**Comment by Rahulghuge94** [comment]
> Ok it did work but in response i am not getting Exchange Order ID - Its Blank for some reason... any idea how to get exchange order id from this "BrokerOrderID"

because order is not executed u will only receive brokerid. exchange order will receive on order get executed.
