### ISSUE TITLE
Not Getting Exchange Order ID 

### ISSUE THREAD

**Issue by jrdinesh** [5paisa/py5paisa#96]
* 5paisa Python SDK version:
* Python version:
* Operating System:

### Description

After successful placement and execution of order i am not getting the exchange order ID in response i get only 'BrokerOrderID". Is there any other way to get exchange order ID.
```

**Comment by qalpesh** [comment]
While placing an order pass unique remote order id (random number) and then fetch order status using the same remote order id. see below code.

random_number = 12872356123
new_odr = Order(order_type=order,
exchange='N',
exchange_segment='D',
scrip_code=scr, quantity=qty, price=prc, is_intraday=intraday,
atmarket=atmkt, is_stoploss_order=slmkt, stoploss_price=slprc,
disqty=0, remote_order_id=random_number)

req_list_ = [

        {
            "Exch": "N",
            "ExchType": "D",
            "ScripCode": scr,
            "RemoteOrderID": random_number
        }]
    order = client.fetch_order_status(req_list_)
    Exchange_order_id = order['OrdStatusResLst'][0]['ExchOrderID']

**Comment by jrdinesh** [comment]
Oh seems unnecessary extra work but ok..
